// Deterministic TypeScript emission with a drift check.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { repoRoot } from "./sources.ts";

export interface GeneratedFile {
	/** Repository-relative path with forward slashes. */
	readonly path: string;
	readonly content: string;
}

export function header(sources: string, importLine = ""): string {
	return `// AUTO-GENERATED by scripts/convert - do not edit.\n// Source: ${sources}\n${importLine === "" ? "" : `${importLine}\n`}\n`;
}

const MAX_INLINE = 110;

function key(name: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) || /^(0|[1-9]\d*)$/.test(name) ? name : JSON.stringify(name);
}

/** JSON-like literal with tab indentation; values that fit on one line stay inline. */
export function literal(value: unknown, depth = 0): string {
	if (value === null || typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	const pad = "\t".repeat(depth + 1);
	const end = "\t".repeat(depth);
	if (Array.isArray(value)) {
		if (value.length === 0) {
			return "[]";
		}
		const items = value.map((v) => literal(v, depth + 1));
		const inline = `[${items.join(", ")}]`;
		return inline.length <= MAX_INLINE && !inline.includes("\n") ? inline : `[\n${items.map((v) => `${pad}${v},`).join("\n")}\n${end}]`;
	}
	const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined);
	if (entries.length === 0) {
		return "{}";
	}
	const parts = entries.map(([k, v]) => `${key(k)}: ${literal(v, depth + 1)}`);
	const inline = `{ ${parts.join(", ")} }`;
	return inline.length <= MAX_INLINE && !inline.includes("\n") ? inline : `{\n${parts.map((p) => `${pad}${p},`).join("\n")}\n${end}}`;
}

export function writeFiles(files: readonly GeneratedFile[]): void {
	for (const file of files) {
		const target = join(repoRoot, file.path);
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, file.content);
	}
}

/** Paths whose on-disk content is missing or differs from the freshly generated content. */
export function findDrift(files: readonly GeneratedFile[]): string[] {
	return files
		.filter((file) => {
			const target = join(repoRoot, file.path);
			return !existsSync(target) || readFileSync(target, "utf8").replace(/\r\n/g, "\n") !== file.content;
		})
		.map((file) => file.path);
}
