// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { BibleBook } from "./types.ts";

export const BIBLE_BOOKS: Readonly<Record<string, BibleBook>> = {
	"Gen": {
		"id": "Gen",
		"name": "Genesis",
		"short": "Gen",
		"chapters": 50,
		"intro": "A reading from Genesis"
	},
	"Ex": {
		"id": "Ex",
		"name": "Exodus",
		"short": "Ex",
		"chapters": 40,
		"intro": "A reading from Exodus"
	},
	"Lev": {
		"id": "Lev",
		"name": "Leviticus",
		"short": "Lev",
		"chapters": 27,
		"intro": "A reading from Levites"
	},
	"Num": {
		"id": "Num",
		"name": "Numbers",
		"short": "Num",
		"chapters": 36,
		"intro": "A reading from Numbers"
	},
	"Deut": {
		"id": "Deut",
		"name": "Deuteronomy",
		"short": "Deut",
		"chapters": 34,
		"intro": "A reading Deuteronomy"
	},
	"Josh": {
		"id": "Josh",
		"name": "Joshua",
		"short": "Josh",
		"chapters": 24,
		"intro": "A reading from Joshua, the son of Nun"
	},
	"Judg": {
		"id": "Judg",
		"name": "Judges",
		"short": "Judg",
		"chapters": 21,
		"intro": "A reading from Judges"
	},
	"Ruth": {
		"id": "Ruth",
		"name": "Ruth",
		"short": "Ruth",
		"chapters": 4,
		"intro": "A reading from Ruth"
	},
	"I_Kings": {
		"id": "I_Kings",
		"name": "I Kingdoms",
		"short": "I Kings",
		"chapters": 31,
		"intro": "A reading from the first Book of Kingdoms"
	},
	"II_Kings": {
		"id": "II_Kings",
		"name": "II Kingdoms",
		"short": "II Kings",
		"chapters": 24,
		"intro": "A reading from the second Book of Kingdoms"
	},
	"III_Kings": {
		"id": "III_Kings",
		"name": "III Kingdoms",
		"short": "III Kings",
		"chapters": 22,
		"intro": "A reading from the third Book of Kingdoms"
	},
	"IV_Kings": {
		"id": "IV_Kings",
		"name": "IV Kingdoms",
		"short": "IV Kings",
		"chapters": 25,
		"intro": "A reading from the fourth Book of Kingdoms"
	},
	"I_Paral": {
		"id": "I_Paral",
		"name": "I Paralipomenon",
		"short": "I Paral",
		"chapters": 29,
		"intro": "A reading from the first Book of Paralipomenon"
	},
	"II_Paral": {
		"id": "II_Paral",
		"name": "II Paralipomenon",
		"short": "II Paral",
		"chapters": 36,
		"intro": "A reading from the second Book of Paraliponmenon"
	},
	"I_Esdra": {
		"id": "I_Esdra",
		"name": "I Esdra",
		"short": "I Esdra",
		"chapters": 10,
		"intro": "A reading from the first Book of Esdras"
	},
	"Nehem": {
		"id": "Nehem",
		"name": "Nehemiah",
		"short": "Nehem",
		"chapters": 13,
		"intro": "A reading from the Prophecy of Nehemiah"
	},
	"II_Esdra": {
		"id": "II_Esdra",
		"name": "II Esdra",
		"short": "II Esdra",
		"chapters": 9,
		"intro": "A reading from the second Book of Esdras"
	},
	"Tobit": {
		"id": "Tobit",
		"name": "Tobit",
		"short": "Tobit",
		"chapters": 14,
		"intro": "A reading from Tobit"
	},
	"Judith": {
		"id": "Judith",
		"name": "Judith",
		"short": "Judith",
		"chapters": 16,
		"intro": "A reading from Judith"
	},
	"Esther": {
		"id": "Esther",
		"name": "Esther",
		"short": "Esther",
		"chapters": 10,
		"intro": "A reading from Esther"
	},
	"Job": {
		"id": "Job",
		"name": "Job",
		"short": "Job",
		"chapters": 42,
		"intro": "A reading from the Job"
	},
	"Psalm": {
		"id": "Psalm",
		"name": "Psalm",
		"short": "Ps",
		"chapters": 151,
		"intro": "Psalm"
	},
	"Prov": {
		"id": "Prov",
		"name": "Proverbs",
		"short": "Prov",
		"chapters": 31,
		"intro": "A reading from Proverbs"
	},
	"Eccles": {
		"id": "Eccles",
		"name": "Ecclesiastes",
		"short": "Eccles",
		"chapters": 12,
		"intro": "A reading from Ecclesiastes"
	},
	"Song": {
		"id": "Song",
		"name": "Song of Songs",
		"short": "Song",
		"chapters": 8,
		"intro": "A reading from the Song of Songs"
	},
	"Wisd": {
		"id": "Wisd",
		"name": "Wisdom of Solomon",
		"short": "Wisd",
		"chapters": 19,
		"intro": "A reading from the Wisdom of Solomon"
	},
	"Sirach": {
		"id": "Sirach",
		"name": "Sirach",
		"short": "Sirach",
		"chapters": 51,
		"intro": "A reading from the Prophecy of Sirach, son of Jesus"
	},
	"Isa": {
		"id": "Isa",
		"name": "Isaiah",
		"short": "Isa",
		"chapters": 66,
		"intro": "A reading from the Prophecy of Isaiah"
	},
	"Jerem": {
		"id": "Jerem",
		"name": "Jeremiah",
		"short": "Jerem",
		"chapters": 52,
		"intro": "A reading from the Prophecy of Jeremiah"
	},
	"Lamen": {
		"id": "Lamen",
		"name": "Lamentations",
		"short": "Lamen",
		"chapters": 5,
		"intro": "A reading from the Lamentations of Jeremiah"
	},
	"Epistle": {
		"id": "Epistle",
		"name": "Epistle of Jeremiah",
		"short": "Epistle",
		"chapters": 1,
		"intro": "A reading from the Epistle of Jeremiah"
	},
	"Baruch": {
		"id": "Baruch",
		"name": "Baruch",
		"short": "Baruch",
		"chapters": 5,
		"intro": "A reading from the Prophecy of Jeremiah"
	},
	"Ezek": {
		"id": "Ezek",
		"name": "Ezekiel",
		"short": "Ezek",
		"chapters": 48,
		"intro": "A reading from the Prophecy of Ezekiel"
	},
	"Dan": {
		"id": "Dan",
		"name": "Daniel",
		"short": "Dan",
		"chapters": 14,
		"intro": "A reading from the Prophecy of Daniel"
	},
	"Hos": {
		"id": "Hos",
		"name": "Hosea",
		"short": "Hos",
		"chapters": 14,
		"intro": "A reading from the Prophecy of Hosea"
	},
	"Joel": {
		"id": "Joel",
		"name": "Joel",
		"short": "Joel",
		"chapters": 3,
		"intro": "A reading from the Prophecy of Joel"
	},
	"Amos": {
		"id": "Amos",
		"name": "Amos",
		"short": "Amos",
		"chapters": 9,
		"intro": "A reading from the Prophecy of Amos"
	},
	"Obad": {
		"id": "Obad",
		"name": "Obadiah",
		"short": "Obad",
		"chapters": 1,
		"intro": "A reading from the Prophecy of Obadiah"
	},
	"Jona": {
		"id": "Jona",
		"name": "Jonah",
		"short": "Jona",
		"chapters": 4,
		"intro": "A reading from the Prophecy of Jonah"
	},
	"Mica": {
		"id": "Mica",
		"name": "Micah",
		"short": "Mica",
		"chapters": 7,
		"intro": "A reading from the Prophecy of Micah"
	},
	"Nahum": {
		"id": "Nahum",
		"name": "Nahum",
		"short": "Nahum",
		"chapters": 3,
		"intro": "A reading from the Prophecy of Nahum"
	},
	"Habak": {
		"id": "Habak",
		"name": "Habakuk",
		"short": "Habak",
		"chapters": 3,
		"intro": "A reading from the Prophecy of Habakuk"
	},
	"Zeph": {
		"id": "Zeph",
		"name": "Zephaniah",
		"short": "Zeph",
		"chapters": 3,
		"intro": "A reading from the Prophecy of Zephaniah"
	},
	"Hagg": {
		"id": "Hagg",
		"name": "Haggai",
		"short": "Hagg",
		"chapters": 2,
		"intro": "A reading from the Prophecy of Haggai"
	},
	"Zech": {
		"id": "Zech",
		"name": "Zechariah",
		"short": "Zech",
		"chapters": 14,
		"intro": "A reading from the Prophecy of Zechariah"
	},
	"Mal": {
		"id": "Mal",
		"name": "Malachi",
		"short": "Mal",
		"chapters": 4,
		"intro": "A reading from the Prophecy of Malachi"
	},
	"I_Macc": {
		"id": "I_Macc",
		"name": "I Maccabees",
		"short": "I Macc",
		"chapters": 16,
		"intro": "A reading from the first Book of Maccabees"
	},
	"II_Macc": {
		"id": "II_Macc",
		"name": "II Maccabees",
		"short": "II Macc",
		"chapters": 15,
		"intro": "A reading from the second Book of Maccabees"
	},
	"III_Macc": {
		"id": "III_Macc",
		"name": "III Maccabees",
		"short": "III Macc",
		"chapters": 7,
		"intro": "A reading from the third Book of Maccabees"
	},
	"III_Esdra": {
		"id": "III_Esdra",
		"name": "III Esdra",
		"short": "III Esdra",
		"chapters": 16,
		"intro": "A reading from the third Book of Esdras"
	},
	"Mt": {
		"id": "Mt",
		"name": "Matthew",
		"short": "Mt",
		"chapters": 28,
		"intro": "A reading from the Holy Gospel according to Matthew"
	},
	"Mk": {
		"id": "Mk",
		"name": "Mark",
		"short": "Mk",
		"chapters": 16,
		"intro": "A reading from the Holy Gospel according to Mark"
	},
	"Lk": {
		"id": "Lk",
		"name": "Luke",
		"short": "Lk",
		"chapters": 24,
		"intro": "A reading from the Holy Gospel according to Luke"
	},
	"Jn": {
		"id": "Jn",
		"name": "John",
		"short": "Jn",
		"chapters": 21,
		"intro": "A reading from the Holy Gospel accoridng to John"
	},
	"Acts": {
		"id": "Acts",
		"name": "Acts",
		"short": "Acts",
		"chapters": 28,
		"intro": "A reading from the Acts of the Apostles"
	},
	"Jas": {
		"id": "Jas",
		"name": "James",
		"short": "Jas",
		"chapters": 5,
		"intro": "A reading from the Epistle of James"
	},
	"I_Pet": {
		"id": "I_Pet",
		"name": "I Peter",
		"short": "I Pet",
		"chapters": 5,
		"intro": "A reading from the the first Epistle of Peter"
	},
	"II_Pet": {
		"id": "II_Pet",
		"name": "II Peter",
		"short": "II Pet",
		"chapters": 3,
		"intro": "A reading from the second Epistle of Peter"
	},
	"I_Jn": {
		"id": "I_Jn",
		"name": "I John",
		"short": "I Jn",
		"chapters": 5,
		"intro": "A reading from the first Epistle of John"
	},
	"II_Jn": {
		"id": "II_Jn",
		"name": "II John",
		"short": "II Jn",
		"chapters": 1,
		"intro": "A reading from the second Epistle of John"
	},
	"III_Jn": {
		"id": "III_Jn",
		"name": "III John",
		"short": "III Jn",
		"chapters": 1,
		"intro": "A reading from the third Epistle of John"
	},
	"Jude": {
		"id": "Jude",
		"name": "Jude",
		"short": "Jude",
		"chapters": 1,
		"intro": "A reading from the Epistle of Jude"
	},
	"Rom": {
		"id": "Rom",
		"name": "Romans",
		"short": "Rom",
		"chapters": 16,
		"intro": "A reading from the Epistle of Paul to the Romans"
	},
	"I_Cor": {
		"id": "I_Cor",
		"name": "I Corinthians",
		"short": "I Cor",
		"chapters": 16,
		"intro": "A reading from the first Epistle of Paul to the Corinthians"
	},
	"II_Cor": {
		"id": "II_Cor",
		"name": "II Corinthians",
		"short": "II Cor",
		"chapters": 13,
		"intro": "A reading from the second Epistle of Paul to the Corinthians"
	},
	"Gal": {
		"id": "Gal",
		"name": "Galatians",
		"short": "Gal",
		"chapters": 6,
		"intro": "A reading from the Epistle of Paul to the Galatians"
	},
	"Eph": {
		"id": "Eph",
		"name": "Ephesians",
		"short": "Eph",
		"chapters": 6,
		"intro": "A reading from the Epistle of Paul to the Ephesians"
	},
	"Philip": {
		"id": "Philip",
		"name": "Philippians",
		"short": "Phil",
		"chapters": 4,
		"intro": "A reading from the Epistle to the Philippians"
	},
	"Col": {
		"id": "Col",
		"name": "Colossians",
		"short": "Col",
		"chapters": 4,
		"intro": "A reading from the Epistle to the Colossians"
	},
	"I_Thess": {
		"id": "I_Thess",
		"name": "I Thessalonians",
		"short": "I Thess",
		"chapters": 5,
		"intro": "A reading from the first Epistle to the Thessalonians"
	},
	"II_Thess": {
		"id": "II_Thess",
		"name": "II Thessalonians",
		"short": "II Thess",
		"chapters": 3,
		"intro": "A reading from the second Epistle to the Thessalonians"
	},
	"I_Tim": {
		"id": "I_Tim",
		"name": "I Timothy",
		"short": "I Tim",
		"chapters": 6,
		"intro": "A reading from the first Epistle to Timothy"
	},
	"II_Tim": {
		"id": "II_Tim",
		"name": "II Timothy",
		"short": "II Tim",
		"chapters": 4,
		"intro": "A reading from the second Epistle to Timothy"
	},
	"Tit": {
		"id": "Tit",
		"name": "Titus",
		"short": "Tit",
		"chapters": 3,
		"intro": "A reading from the Epistle to Titus"
	},
	"Philemon": {
		"id": "Philemon",
		"name": "Philemon",
		"short": "Philemon",
		"chapters": 1,
		"intro": "A reading from the Epistle to Philemon"
	},
	"Heb": {
		"id": "Heb",
		"name": "Hebrews",
		"short": "Heb",
		"chapters": 13,
		"intro": "A reading from the Epistle to the Hebrews"
	},
	"Apoc": {
		"id": "Apoc",
		"name": "Apocalypse",
		"short": "Apoc",
		"chapters": 22,
		"intro": "A reading from the Book of Revelations"
	},
	"Composite": {
		"id": "Composite",
		"name": "Composite",
		"short": "Composite",
		"chapters": 8
	}
} as const;

export const BIBLE_BOOK_ALIASES: Readonly<Record<string, string>> = {
	"Acts": "Acts",
	"Amos": "Amos",
	"Apoc": "Apoc",
	"Apocalypse": "Apoc",
	"Baruch": "Baruch",
	"Col": "Col",
	"Colossians": "Col",
	"Composite": "Composite",
	"Dan": "Dan",
	"Daniel": "Dan",
	"Deut": "Deut",
	"Deuteronomy": "Deut",
	"Eccles": "Eccles",
	"Ecclesiastes": "Eccles",
	"Eph": "Eph",
	"Ephesians": "Eph",
	"Epistle": "Epistle",
	"Epistle of Jeremiah": "Epistle",
	"Esther": "Esther",
	"Ex": "Ex",
	"Exodus": "Ex",
	"Ezek": "Ezek",
	"Ezekiel": "Ezek",
	"Gal": "Gal",
	"Galatians": "Gal",
	"Gen": "Gen",
	"Genesis": "Gen",
	"Habak": "Habak",
	"Habakuk": "Habak",
	"Hagg": "Hagg",
	"Haggai": "Hagg",
	"Heb": "Heb",
	"Hebrews": "Heb",
	"Hos": "Hos",
	"Hosea": "Hos",
	"I Cor": "I_Cor",
	"I Corinthians": "I_Cor",
	"I Esdra": "I_Esdra",
	"I Jn": "I_Jn",
	"I John": "I_Jn",
	"I Kingdoms": "I_Kings",
	"I Kings": "I_Kings",
	"I Macc": "I_Macc",
	"I Maccabees": "I_Macc",
	"I Paral": "I_Paral",
	"I Paralipomenon": "I_Paral",
	"I Pet": "I_Pet",
	"I Peter": "I_Pet",
	"I Thess": "I_Thess",
	"I Thessalonians": "I_Thess",
	"I Tim": "I_Tim",
	"I Timothy": "I_Tim",
	"II Cor": "II_Cor",
	"II Corinthians": "II_Cor",
	"II Esdra": "II_Esdra",
	"II Jn": "II_Jn",
	"II John": "II_Jn",
	"II Kingdoms": "II_Kings",
	"II Kings": "II_Kings",
	"II Macc": "II_Macc",
	"II Maccabees": "II_Macc",
	"II Paral": "II_Paral",
	"II Paralipomenon": "II_Paral",
	"II Pet": "II_Pet",
	"II Peter": "II_Pet",
	"II Thess": "II_Thess",
	"II Thessalonians": "II_Thess",
	"II Tim": "II_Tim",
	"II Timothy": "II_Tim",
	"III Esdra": "III_Esdra",
	"III Jn": "III_Jn",
	"III John": "III_Jn",
	"III Kingdoms": "III_Kings",
	"III Kings": "III_Kings",
	"III Macc": "III_Macc",
	"III Maccabees": "III_Macc",
	"III_Esdra": "III_Esdra",
	"III_Jn": "III_Jn",
	"III_Kings": "III_Kings",
	"III_Macc": "III_Macc",
	"II_Cor": "II_Cor",
	"II_Esdra": "II_Esdra",
	"II_Jn": "II_Jn",
	"II_Kings": "II_Kings",
	"II_Macc": "II_Macc",
	"II_Paral": "II_Paral",
	"II_Pet": "II_Pet",
	"II_Thess": "II_Thess",
	"II_Tim": "II_Tim",
	"IV Kingdoms": "IV_Kings",
	"IV Kings": "IV_Kings",
	"IV_Kings": "IV_Kings",
	"I_Cor": "I_Cor",
	"I_Esdra": "I_Esdra",
	"I_Jn": "I_Jn",
	"I_Kings": "I_Kings",
	"I_Macc": "I_Macc",
	"I_Paral": "I_Paral",
	"I_Pet": "I_Pet",
	"I_Thess": "I_Thess",
	"I_Tim": "I_Tim",
	"Isa": "Isa",
	"Isaiah": "Isa",
	"James": "Jas",
	"Jas": "Jas",
	"Jerem": "Jerem",
	"Jeremiah": "Jerem",
	"Jn": "Jn",
	"Job": "Job",
	"Joel": "Joel",
	"John": "Jn",
	"Jona": "Jona",
	"Jonah": "Jona",
	"Josh": "Josh",
	"Joshua": "Josh",
	"Jude": "Jude",
	"Judg": "Judg",
	"Judges": "Judg",
	"Judith": "Judith",
	"Lamen": "Lamen",
	"Lamentations": "Lamen",
	"Lev": "Lev",
	"Leviticus": "Lev",
	"Lk": "Lk",
	"Luke": "Lk",
	"Mal": "Mal",
	"Malachi": "Mal",
	"Mark": "Mk",
	"Matthew": "Mt",
	"Mica": "Mica",
	"Micah": "Mica",
	"Mk": "Mk",
	"Mt": "Mt",
	"Nahum": "Nahum",
	"Nehem": "Nehem",
	"Nehemiah": "Nehem",
	"Num": "Num",
	"Numbers": "Num",
	"Obad": "Obad",
	"Obadiah": "Obad",
	"Phil": "Philip",
	"Philemon": "Philemon",
	"Philip": "Philip",
	"Philippians": "Philip",
	"Prov": "Prov",
	"Proverbs": "Prov",
	"Ps": "Psalm",
	"Psalm": "Psalm",
	"Rom": "Rom",
	"Romans": "Rom",
	"Ruth": "Ruth",
	"Sirach": "Sirach",
	"Song": "Song",
	"Song of Songs": "Song",
	"Tit": "Tit",
	"Titus": "Tit",
	"Tobit": "Tobit",
	"Wisd": "Wisd",
	"Wisdom of Solomon": "Wisd",
	"Zech": "Zech",
	"Zechariah": "Zech",
	"Zeph": "Zeph",
	"Zephaniah": "Zeph"
} as const;
