// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { Command } from "./types.ts";

export const DIVINE_LITURGY_COMMANDS: ReadonlyArray<Command> = [
	{
		"name": "Transfer",
		"value": "nday >= 52 || nday < -55",
		"cmd": "GS == 1",
		"comment": "This determines whether the sequential readings may be skipped or transferred."
	},
	{
		"name": "Transfer",
		"value": "nday >= 52 || nday < -55",
		"cmd": "GS == 0",
		"comment": "This determines whether the sequential readings may be skipped or transferred."
	},
	{
		"name": "Suppress",
		"value": "doy == 4 && dow != 0 && dow != 6",
		"cmd": "GS == 1",
		"comment": "Eve of Theophany can have seq. readings on Sat. (see Table 25b, 2019) and on Sun. (see Table 24b, 2087)"
	},
	{
		"name": "Suppress",
		"value": "doy == 357 && dow != 6",
		"cmd": "GS == 1",
		"comment": "Eve of Nativity can have seq. readings on Sat. (see Table 27a, 2084)"
	},
	{
		"name": "Suppress",
		"value": "(doy == 358 || doy == 5)",
		"comment": "Nativity and Theophany never have seq. readings"
	},
	{
		"name": "Suppress",
		"value": "(doy == 256 || doy == 217) && dow == 0",
		"comment": "Suppress seq. readings if Exaltation or Transfiguration falls on Sunday"
	},
	{
		"name": "Class3Transfers",
		"value": "!(doy == 358 || doy == 357 || doy == 4 || doy == 5 || doy == 256 || doy == 217) && ((dRank >= 5 && dow != 0) || dRank == 8)",
		"cmd": "GS == 1 || GS == 0"
	},
	{
		"name": "Class3Transfers",
		"value": "(doy == 3 && dow == 5) || (doy == 356 && dow == 5)",
		"cmd": "GS == 1 || GS == 0",
		"comment": "There is no Liturgy on Friday when the Royal Hours occur. The readings are moved to Thursday."
	},
	{
		"name": "Class3Transfers",
		"value": "(doy == 256 || doy == 217) && dow != 0",
		"comment": "Exaltation and Transfiguration readings are only transferred if it's not a Sunday"
	},
	{
		"name": "TransferRulesB",
		"value": "dow != 0 && !(nday >= -63 && nday <= 0) && doy != 338",
		"cmd": "GS == 1",
		"comment": "This determines the rules used to transfer the readings to the previous day. Note that St. Nicholas's day has a special set of rules"
	},
	{
		"name": "TransferRulesF",
		"value": "!(nday >= -63 && nday <= 0) && (dow == 2  && doy != 339) || ((doy == 340 && (dow != 0 && dow != 2)))",
		"cmd": "GS == 1",
		"comment": "This determines the rules used to transfer the readings to the next day (forwards). Note that St. Nicholas's day has a special set of rules."
	},
	{
		"name": "TransferRulesB",
		"value": "dow != 0 && !(nday >= -63 && nday <= 0) && doy != 338",
		"cmd": "GS == 0",
		"comment": "This determines the rules used to transfer the readings to the previous day. Note that St. Nicholas's day has a special set of rules"
	},
	{
		"name": "TransferRulesF",
		"value": "!(nday >= -63 && nday <= 0) && (dow == 2  && doy != 339) || ((doy == 340 && (dow != 0 && dow != 2)))",
		"cmd": "GS == 0",
		"comment": "This determines the rules used to transfer the readings to the next day (forwards). Note that St. Nicholas's day has a special set of rules."
	}
] as const;
