// AUTO-GENERATED by scripts/codegen/dow-movables.ts — do not edit by hand.
// Decomposed from DAY_FACTS_BY_ISO (2025-2030 vendored window).
// Generated: 2026-10-02T04:03:32.930Z
// DOW-shift / DOW-nearest-Julian entries captured: 43
// Skipped (no rule inferred): 3

import type { Commemoration } from "./dayFacts.ts";

/** DOW-shift / DOW-nearest-Julian rule for a movable commemoration. */
export type DowMovableRule =
	| { readonly kind: "dow-after"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number }
	| { readonly kind: "dow-after-strict"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number }
	| { readonly kind: "dow-before"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number }
	| { readonly kind: "dow-before-strict"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number }
	| { readonly kind: "dow-nearest"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number }
	| { readonly kind: "dow-window"; readonly dow: number; readonly julianMonth: number; readonly julianDay: number; readonly minDiff: number; readonly maxDiff: number }
	| { readonly kind: "nday-set"; readonly ndays: readonly number[] };

/** One commemoration tagged with its DOW-shift rule. */
export interface DowMovable {
	readonly rule: DowMovableRule;
	readonly commem: Commemoration;
}

/** DOW-shift / DOW-nearest-Julian commemoration overlay. Each entry is
 *  tested against the current DayContext at runtime by the matcher in
 *  src/engine/commemorations.ts. */
export const DOW_MOVABLES: readonly DowMovable[] = [
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":7,"julianDay":16},
		commem: { rank: "0", text: "Commemoration of the Holy Fathers of the First Six Councils ( movable holiday on Sunday closest to July 16 ).", minor: false, lives: [{"name":"Holy Fathers","slug":"Epiphany/e07171"}] },
	},
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":10,"julianDay":11},
		commem: { rank: "1", text: "Commemoration of the Holy Fathers of the Seventh Ecumenical Council (787).", minor: false, lives: [{"name":"Seventh Ecumenical Council","slug":"Epiphany/e10121-SeventhEcumenicalCouncil"}] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":6,"julianMonth":10,"julianDay":26},
		commem: { rank: "1", text: "Demetrius (Parental) Saturday. Remembrance of the dead.", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":6,"julianDay":27},
		commem: { rank: "1", text: "Hieromartirs Neophytus, Jonah, Neophytus, Jonah, and Parthenius of Lampsacus ( movable holiday on the 1st Sunday after June 27th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":8,"julianDay":15},
		commem: { rank: "0", text: "Icon of the Mother of God \"Enlightener of Minds\" ( movable holiday on the Sunday after August 15 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":6,"julianDay":18},
		commem: { rank: "0", text: "Korobeinikov-Kazan Icon of the Most Holy Theotokos ( movable holiday on the Saturday after to June 18th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":1,"julianDay":25},
		commem: { rank: "5", text: "New Martyrs and Confessors of Russian Church ( movable holiday on the Sunday closest to January 25th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"nday-set","ndays":[-36,-29,-22]},
		commem: { rank: "1", text: "Parents’ Saturday. Remembrance of the dead .", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":1,"julianDay":25},
		commem: { rank: "0", text: "Remembrance of all the departed who suffered in the years of persecution for faith in Christ.", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":12,"julianDay":25},
		commem: { rank: "1", text: "Righteous Joseph the Betrothed, Holy Righteous David the King, and James the Brother of the Lord ( movable holiday on the Sunday after the Nativity of our Lord God and Savior Jesus Christ ).", minor: false, lives: [{"name":"Joseph","slug":"Epiphany/e12261-02"},{"name":"David","slug":"Epiphany/e12261-03"},{"name":"James","slug":"Epiphany/e12261-04"}] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":6,"julianMonth":1,"julianDay":6},
		commem: { rank: "0", text: "Saturday after the Baptism of Our Lord and God and Saviour Jesus Christ", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":6,"julianMonth":12,"julianDay":25},
		commem: { rank: "0", text: "Saturday after the Nativity of our Lord God and Savior Jesus Christ", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":6,"julianMonth":9,"julianDay":14},
		commem: { rank: "0", text: "Saturday after the Universal Elevation of the Precious and Life-Creating Cross of the Lord", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":6,"julianMonth":1,"julianDay":6},
		commem: { rank: "0", text: "Saturday before the Theophany.", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":6,"julianMonth":9,"julianDay":14},
		commem: { rank: "0", text: "Saturday before the Universal Elevation of the Precious and Life-Creating Cross of the Lord", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before","dow":6,"julianMonth":12,"julianDay":24},
		commem: { rank: "0", text: "Saturday the Nativity of our Lord God and Savior Jesus Christ", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":6,"julianDay":29},
		commem: { rank: "1", text: "St. Arsenius , bishop of Tver ( movable holiday on the 1st Sunday after June 29th ).", minor: false, lives: [{"name":"Arsenius","slug":"Epiphany/e06291"}] },
	},
	{
		rule: {"kind":"dow-nearest","dow":6,"julianMonth":6,"julianDay":19},
		commem: { rank: "1", text: "St. John of Shanghai and San Francisco the Wonderworker ( movable holiday on the Saturday closest to June 19th ).", minor: false, lives: [{"name":"John","slug":"Epiphany/e06167"}] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":1,"julianDay":6},
		commem: { rank: "0", text: "Sunday after the Baptism of Our Lord and God and Saviour Jesus Christ", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":12,"julianDay":25},
		commem: { rank: "1", text: "Sunday after the Nativity of our Lord God and Savior Jesus Christ, holy ancestors.", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":9,"julianDay":14},
		commem: { rank: "0", text: "Sunday after the Universal Elevation of the Precious and Life-Creating Cross of the Lord", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-window","dow":0,"julianMonth":1,"julianDay":6,"minDiff":-4,"maxDiff":-1},
		commem: { rank: "0", text: "Sunday before the Baptism of Our Lord and God and Saviour Jesus Christ", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before","dow":0,"julianMonth":12,"julianDay":24},
		commem: { rank: "0", text: "Sunday before the Nativity of our Lord God and Savior Jesus Christ.", minor: false, lives: [{"name":"Sunday before the Nativity","slug":"Epiphany/e12181-SundaybeforetheNativity"}] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":0,"julianMonth":9,"julianDay":14},
		commem: { rank: "0", text: "Sunday before the Universal Elevation of the Precious and Life-Creating Cross of the Lord", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":9,"julianDay":7},
		commem: { rank: "0", text: "Synaxis of All Saints of Altai ( movable holiday on the Sunday after September 7 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":0,"julianMonth":8,"julianDay":26},
		commem: { rank: "1", text: "Synaxis of all saints of Moscow ( movable holiday on the Sunday before August 26 th , Russian Orthodox Church - the Moscow Patriarchate ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":8,"julianDay":26},
		commem: { rank: "0", text: "Synaxis of all saints of Nizhny Novgorod ( movable holiday on the Sunday after August 26 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":1,"julianDay":29},
		commem: { rank: "0", text: "Synaxis of All Saints of Perm Metropolia ( movable holiday on the Sunday after January 29 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":8,"julianDay":31},
		commem: { rank: "0", text: "Synaxis of All Saints of Saratov ( movable holiday on the Sunday nearest to August 31 st ) .", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before","dow":0,"julianMonth":9,"julianDay":29},
		commem: { rank: "0", text: "Synaxis of All Saints Who Shone Forth in the Spanish and Portuguese Lands ( movable holiday on the Sunday before September 29 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":5,"julianDay":19},
		commem: { rank: "0", text: "Synaxis of Hieromartyrs of Kholmsk and Podliash ( movable holiday on the Sunday after May 19th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":9,"julianDay":3},
		commem: { rank: "1", text: "Synaxis of New Martyrs and Confessors of Kazakhstan ( movable holiday on the Sunday after September 3rd ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-nearest","dow":0,"julianMonth":11,"julianDay":10},
		commem: { rank: "1", text: "Synaxis of Saints of Alania ( movable holiday on the Sunday nearest to November 10 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":9,"julianDay":27},
		commem: { rank: "0", text: "Synaxis of Saints of Chelyabinsk Metropolia ( movable holiday on the Sunday after to September 27 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":0,"julianMonth":8,"julianDay":18},
		commem: { rank: "0", text: "Synaxis of saints of Kemerovo ( movable holiday on the Sunday before August 18 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":9,"julianDay":28},
		commem: { rank: "0", text: "Synaxis of Saints of Kuban Metropolia ( movable holiday on the Sunday after to September 28 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":0,"julianMonth":7,"julianDay":28},
		commem: { rank: "1", text: "Synaxis of saints of Smolensk ( movable holiday on the Sunday before July 28th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":6,"julianDay":29},
		commem: { rank: "1", text: "Synaxis of saints of Tver ( movable holiday on the 1st Sunday after June 29th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after","dow":0,"julianMonth":8,"julianDay":6},
		commem: { rank: "0", text: "Synaxis of saints of Valaam Monastery ( movable holiday on the Sunday after August 6 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before-strict","dow":0,"julianMonth":9,"julianDay":6},
		commem: { rank: "0", text: "Translation of the relics of Prince Peter (1228) and Princess Febronia (tonsured David and Euphrosyne), wonderworkers of Murom ( movable holiday on the Sunday before September 6 th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":6,"julianMonth":1,"julianDay":6},
		commem: { rank: "1", text: "Venerable Pachomius of Kensk (16th c.) ( movable holiday on the Saturday after the Baptism of Our Lord and God and Saviour Jesus Christ ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-after-strict","dow":0,"julianMonth":6,"julianDay":29},
		commem: { rank: "1", text: "Venerables Tikhon, Basil and Nikon Sokolovsky (16th c.) ( movable holiday on the 1st Sunday after June 29th ).", minor: false, lives: [] },
	},
	{
		rule: {"kind":"dow-before","dow":0,"julianMonth":12,"julianDay":17},
		commem: { rank: "1", text: "Week of Holy Forefathers", minor: false, lives: [{"name":"Week of Holy Forefathers","slug":"Epiphany/e12111-WeekofHolyForefathers"}] },
	},
];

/** Total number of DOW-shift movable commemorations captured. */
export const DOW_MOVABLES_COUNT = 43;
