// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { DayEntry } from "./types.ts";

export const MENAION: Readonly<Record<string, DayEntry>> = {
	"01-01": {
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "010101"
			},
			{
				"sIds": [
					"772426"
				],
				"cId": "772426"
			},
			{
				"sIds": [
					"772440"
				],
				"cId": "772440"
			},
			{
				"sIds": [
					"772444"
				],
				"cId": "772444",
				"src": "G"
			},
			{
				"sIds": [
					"772447"
				],
				"cId": "772447",
				"src": "G"
			},
			{
				"sIds": [
					"772446"
				],
				"cId": "772446",
				"src": "G"
			},
			{
				"sIds": [
					"772443"
				],
				"cId": "772443",
				"src": "G"
			},
			{
				"sIds": [
					"772441"
				],
				"cId": "772441",
				"src": "R"
			},
			{
				"sIds": [
					"772427"
				],
				"cId": "772427",
				"src": "R"
			},
			{
				"sIds": [
					"772428",
					"772429",
					"772430"
				],
				"cId": "010102",
				"src": "R"
			},
			{
				"sIds": [
					"772431",
					"772432",
					"772433",
					"772434",
					"772435",
					"772436",
					"772437",
					"772438",
					"772439"
				],
				"cId": "010103",
				"src": "R"
			},
			{
				"sIds": [
					"010109"
				],
				"cId": "010109",
				"src": "U"
			}
		]
	},
	"01-02": {
		"saints": [
			{
				"sIds": [
					"5"
				],
				"cId": "010201"
			},
			{
				"sIds": [
					"772455"
				],
				"cId": "772455"
			},
			{
				"sIds": [
					"772456"
				],
				"cId": "772456"
			},
			{
				"sIds": [
					"772457"
				],
				"cId": "010202"
			},
			{
				"sIds": [
					"772458"
				],
				"cId": "772458"
			},
			{
				"sIds": [
					"772459"
				],
				"cId": "772459"
			}
		]
	},
	"01-30": {
		"saints": [
			{
				"sIds": [
					"772426",
					"1650102",
					"1650103"
				],
				"cId": "013001",
				"cmd": "nday != -51 && nday != -53"
			}
		]
	},
	"12-30": {
		"saints": [
			{
				"sIds": [],
				"cId": "123001"
			}
		]
	},
	"12-31": {
		"saints": [
			{
				"sIds": [],
				"cId": "123101"
			},
			{
				"sIds": [
					"772425"
				],
				"cId": "772425"
			},
			{
				"sIds": [
					"772423"
				],
				"cId": "772423"
			},
			{
				"sIds": [
					"772424"
				],
				"cId": "772424"
			}
		]
	}
} as const;
