// AUTO-GENERATED by scripts/codegen/paschal-movables.ts — do not edit by hand.
// Decomposed from DAY_FACTS_BY_ISO (2025-2027 vendored window).
// Generated: 2026-10-02T03:30:41.666Z

import type { Commemoration } from "./dayFacts.ts";

/** Paschal/triodion-cycle movable commemoration overlay, keyed by `nday`
 *  (days-relative-to-Pascha, Pascha=0). A text lives here iff every one
 *  of its vendored occurrences shared the same nday value while landing
 *  on different Julian dates. DOW-nearest-Julian-date patterns go to
 *  Phase C4. */
export const PASCHAL_MOVABLES_CYCLE: ReadonlyMap<number, readonly Commemoration[]> = new Map([
	[-69, [
		{ rank: "0", text: "Entire week, fast-free.", minor: false, lives: [] },
	]],
	[-55, [
		{ rank: "0", text: "Maslenitsa, entire week.", minor: false, lives: [] },
	]],
	[-52, [
		{ rank: "1", text: "Venerable Shio Mgvime (6th c.) (Georgia) ( movable holiday on Thursday of the Cheese-fare Week ).", minor: false, lives: [{"name":"Shio","slug":"Epiphany/p-52"}] },
	]],
	[-50, [
		{ rank: "1", text: "All of the venerable fathers, lit up with great deeds ( movable holiday on Saturday of the Cheese-fare Week ).", minor: false, lives: [] },
	]],
	[-43, [
		{ rank: "1", text: "Great Martyr Theodore Tyro (306) ( movable holiday on Saturday of the 1st week of the Great Lent ).", minor: false, lives: [{"name":"Theodore","slug":"Epiphany/p-43"}] },
	]],
	[-42, [
		{ rank: "1", text: "\"Cyprus\" Icon of the Most Holy Theotokos from the village Staromniy, Moscow region ( movable holiday on the 1st Sunday of the Great Lent ).", minor: false, lives: [{"name":"\"Cyprus\"","slug":"Epiphany/p-42"}] },
	]],
	[-35, [
		{ rank: "1", text: "St. Gregory Palamas the Archbishop of Thessalonica ( movable holiday on the 2nd Sunday of the Great Lent ).", minor: false, lives: [{"name":"Gregory","slug":"Epiphany/p-35"}] },
		{ rank: "1", text: "Synaxis of all Venerable Fathers of the Kiev Caves ( movable holiday on the 2nd Sunday of the Great Lent ).", minor: false, lives: [] },
	]],
	[-21, [
		{ rank: "1", text: "Venerable John Lestvichnik ( movable holiday on the 4th Sunday of the Great Lent ).", minor: false, lives: [{"name":"John","slug":"Epiphany/p-21"}] },
	]],
	[-14, [
		{ rank: "1", text: "Venerable Mary of Egypt ( movable holiday on the 5th Sunday of the Great Lent ).", minor: false, lives: [{"name":"Mary","slug":"Epiphany/p-14"}] },
	]],
	[-8, [
		{ rank: "o", text: "Feast of the Georgian Language ( movable holiday on the Lazarus Saturday ) ( Georgia ).", minor: true, lives: [] },
	]],
	[1, [
		{ rank: "0", text: "Entire week, fast-free .", minor: false, lives: [] },
	]],
	[2, [
		{ rank: "1", text: "\"Iveron\" Icon of the Most Holy Theotokos ( movable holiday on the Tuesday of the Bright Week ).", minor: false, lives: [{"name":"\"Iveron\"","slug":"Epiphany/p+02-01"}] },
		{ rank: "1", text: "\"Shuisky\" Icon of the Most Holy Theotokos ( movable holiday on the Tuesday of the Bright Week ).", minor: false, lives: [{"name":"\"Shuisky\"","slug":"Epiphany/p+02-03"}] },
		{ rank: "1", text: "Blessed Martyrs and Fathers of the St. David-Gareji Monastery (17th c.) (Georgia) ( movable holiday on the Tuesday of the Bright Week ).", minor: false, lives: [{"name":"Martyrs","slug":"Epiphany/p+02-02"},{"name":"Fathers","slug":"Epiphany/p+02-02"}] },
	]],
	[3, [
		{ rank: "1", text: "\"Kasperov\" Icon of the Most Holy Theotokos ( movable holiday on the Wednesday of the Bright Week ).", minor: false, lives: [{"name":"\"Kasperov\"","slug":"Epiphany/p+03"}] },
		{ rank: "1", text: "Synaxis of the Venerable Fathers of the Holy Mount Sinai ( movable holiday on the Wednesday of the Bright Week ).", minor: false, lives: [] },
	]],
	[5, [
		{ rank: "1", text: "\"Life- giving Spring\" Icon of the Most Holy Theotokos ( movable holiday on the Friday of the Bright Week ).", minor: false, lives: [] },
		{ rank: "1", text: "\"Pochaev\" Icon of the Most Holy Theotokos ( movable holiday on the Friday of the Bright Week ).", minor: false, lives: [{"name":"\"Pochaev\"","slug":"Epiphany/p+05-03"}] },
		{ rank: "1", text: "Commemoration of the renewal (sanctification) of the Holy Theotokos temple near the Life-giving Spring in Constantinople (5th c.) ( movable holiday on the Friday of the Bright Week ).", minor: false, lives: [] },
	]],
	[7, [
		{ rank: "o", text: "\"Sladkoe lobzanie\" Icon of the Most Holy Theotokos (9th c.) ( movable holiday on the Antipascha ).", minor: true, lives: [] },
	]],
	[14, [
		{ rank: "o", text: "All Saints of Thessalonica ( celebration on the 3rd Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "o", text: "New Hieromartyr Seraphim, archbishop of Phanarion and Neochorion ( celebration on the 3rd Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "o", text: "New Martyr Demetrius of Peloponnesus (1803) ( celebration on the 3rd Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "o", text: "New Monk-martyr Elias (Ardunis) of Mt. Athos and Kalamata (1688) ( celebration on the 3rd Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "1", text: "Right-believing Tamara , Queen of Georgia ( movable holiday on the Sunday of Myrrh-Bearing Women ).", minor: false, lives: [{"name":"Tamara","slug":"Epiphany/p+14"}] },
		{ rank: "0", text: "Sts. Mary and Martha , sisters of St. Lazarus (1st c.) ( movable holiday on the Sunday of Myrrh-Bearing Women ).", minor: false, lives: [{"name":"Mary","slug":"Epiphany/p+14-2"},{"name":"Martha","slug":"Epiphany/p+14-2"}] },
		{ rank: "1", text: "Sts. Myrrh-Bearing Women, righteous Joseph of Arimathea and Nicodemus ( celebration on the 3rd Sunday of Pascha ).", minor: false, lives: [] },
	]],
	[21, [
		{ rank: "o", text: "All Saints of Euboea ( movable holiday on the 4th Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "o", text: "New Martyr Theodore of Bizantium, who died at Mitilene (1795) ( movable holiday on the 4th Sunday of Pascha ) ( Greek ).", minor: true, lives: [] },
		{ rank: "1", text: "Righteous Tabitha (1st c.) ( movable holiday on the 4th Sunday of Pascha ).", minor: false, lives: [{"name":"Tabitha","slug":"Epiphany/p+21-02"}] },
		{ rank: "1", text: "Translation of the relics of Martyr Abramius of Bulgaria (1230) ( movable holiday on the 4th Sunday of Pascha ).", minor: false, lives: [{"name":"Abramius","slug":"Epiphany/p+21-01"}] },
	]],
	[24, [
		{ rank: "1", text: "\"Mozdok\" and \"Dubensk-Krasnogorodsk\" (17th c.) Icons of the Most Holy Theotokos ( movable holiday on the Prepolovenie – Mid-Pentecost ).", minor: false, lives: [{"name":"\"Mozdok\"","slug":"Epiphany/p+24-01"}] },
	]],
	[27, [
		{ rank: "0", text: "Synaxis of New Martyrs of Butovo ( movable holiday on the Saturday after the Pascha ).", minor: false, lives: [] },
	]],
	[39, [
		{ rank: "1", text: "Holy Georgian Martyrs of Persia (17th-18th c.) ( movable holiday on the day of the Holy Ascension ) ( Georgia ).", minor: false, lives: [{"name":"Georgian Martyrs","slug":"Epiphany/p+39"}] },
	]],
	[42, [
		{ rank: "1", text: "\"Chelnsk\" Icon of the Most Holy Theotokos named \"Tenderness\" ( movable holiday on the 7th Sunday of Pascha ).", minor: false, lives: [{"name":"\"Tenderness\"","slug":"Epiphany/p+42"}] },
	]],
	[45, [
		{ rank: "1", text: "Venerable Dodo of the St. David-Gareji Monastery, Georgia (596) ( movable holiday on the Wednesday of Holy Ascension ).", minor: false, lives: [{"name":"Dodo","slug":"Epiphany/p+45"}] },
	]],
	[46, [
		{ rank: "1", text: "Venerable David of the Gareji Monastery and Lukiane, Georgia (6th-7th c.) ( movable holiday on the Thursday of Holy Ascension ).", minor: false, lives: [{"name":"David","slug":"Epiphany/p+46-StDavidGareji"}] },
	]],
	[49, [
		{ rank: "o", text: "\"Lesna\" Icon of the Most Holy Theotokos (1696) (movable holiday on the Trinity Sunday) .", minor: true, lives: [{"name":"\"Lesna\"","slug":"Epiphany/p+49"}] },
		{ rank: "o", text: "Holy Fathers and Mothers of Atchara (18th c.) (movable holiday on the Trinity Sunday) (Georgia) .", minor: true, lives: [{"name":"Fathers and Mothers","slug":"Epiphany/p+49-02"}] },
	]],
	[50, [
		{ rank: "1", text: "\"Tupichevsk\" and \"Cyprus\" Icon of the Most Holy Theotokos ( movable holiday on the Day Of the Holy Spirit ).", minor: false, lives: [{"name":"\"Cyprus\"","slug":"Epiphany/p+50"}] },
	]],
	[53, [
		{ rank: "1", text: "Icon of the Most Holy Theotokos \"Surety of Sinners\" in Korets (1622) ( movable holiday on Thursday of the 1-st week of the Pentecost ).", minor: false, lives: [] },
	]],
	[56, [
		{ rank: "1", text: "Icons of the Mother of God \"the Consoler of angry hearts\" and \"the Unbreakable Wall\" ( movable holiday on the Sunday of All Saints ).", minor: false, lives: [{"name":"\"the Consoler of angry hearts\"","slug":"Epiphany/p+56"}] },
	]],
	[61, [
		{ rank: "1", text: "\"Tabynsk\" and \"Kursk-Root\" Icons of the Most Holy Theotokos ( movable holiday on the 9th Friday of Pascha ).", minor: false, lives: [{"name":"\"Kursk-Root\"","slug":"Epiphany/p+61-02"}] },
		{ rank: "1", text: "Venerable Barlaam of Khutyn (1192) ( movable holiday on the 1st Friday of Apostles' Fast ).", minor: false, lives: [{"name":"Barlaam","slug":"Epiphany/p+61-01"}] },
	]],
	[63, [
		{ rank: "o", text: "\"Kaluga\" Icon of the Most Holy Theotokos (1771) ( movable holiday on the first Sunday of the Apostles' Fast ).", minor: true, lives: [{"name":"\"Kaluga\"","slug":"Epiphany/p+63"}] },
		{ rank: "o", text: "All venerable and holy Fathers of Bulgaria ( movable holiday on the 2nd Sunday of Pentecost ).", minor: true, lives: [] },
		{ rank: "0", text: "All venerable and holy Fathers of the Holy Mount Athos ( movable holiday on the 2nd Sunday of Pentecost ).", minor: false, lives: [] },
	]],
	[70, [
		{ rank: "1", text: "Celebration in Vologda to the venerable fathers of Vologda ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [] },
		{ rank: "o", text: "New Martyrs of the Turkish Yoke ( movable holiday on the 3rd Sunday of Pentecost ).", minor: true, lives: [] },
		{ rank: "1", text: "Synaxis of Novgorod Hierarchs ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [{"name":"Synaxis of Novgorod Hierarchs","slug":"February/10-06"}] },
		{ rank: "1", text: "Synaxis of Saints of Belorussia ( movable holiday on the 3rd Sunday of Pentecost ): St. Menas, Bishop of Polotsk (1116), St Dionysius bishop Polotsk (1182), Cyril Bishop of Turiv (1183), Lavrenti Bishop of Turiv (1184), Symeon bishop Polotsk (1289); Blessed Great Prince Rostislav (baptize as Michael), of Kiev (1167); Venerable Martyrs Athanasius, Higumen of Brest (1648), Makarius Kabevsky Higumen of Pinsk (1678); Venerable Martin Turovsky (1150), Elise Lavrishevsk (1250); venerable Ephrosinia of Polotsk (1173), Martyr child Gabriel Belostotsky (1690); righteous Juliana princess of Olshansk (1550), and Sophia princess of Slutsk (1612).", minor: false, lives: [] },
		{ rank: "1", text: "Synaxis of Saints of Pskov ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [] },
		{ rank: "1", text: "Synaxis of Saints of St. Petersburg ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [] },
		{ rank: "1", text: "Synaxis of Saints of the Lands of Udmurtia ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [] },
		{ rank: "1", text: "Synaxis of Saints of Volgograd ( movable holiday on the 3rd Sunday of Pentecost ).", minor: false, lives: [] },
	]],
	[77, [
		{ rank: "0", text: "Synaxis of All Saints of Pskov-Pechers ( movable holiday on the 4th Sunday of Pentecost ).", minor: false, lives: [] },
	]],
]);

/** Total number of paschal/triodion movable entries captured. */
export const PASCHAL_MOVABLES_COUNT = 57;
