// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { DayEntry } from "./types.ts";

export const PENTECOSTARION: ReadonlyArray<DayEntry | null> = [
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9001",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9002",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9003",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9004",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9005",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9006",
				"tone": "-1"
			},
			{
				"sIds": [
					"1"
				],
				"cId": "772121"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9007",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9008",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9009",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9010",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9011",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9012",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9013",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9014",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9015",
				"tone": "2"
			},
			{
				"sIds": [
					"772687"
				],
				"cId": "901501"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9016",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9017",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9018",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9019",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9020",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9021",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9022",
				"tone": "3"
			},
			{
				"sIds": [
					"771525"
				],
				"cId": "902201"
			},
			{
				"sIds": [
					"771526"
				],
				"cId": "902202"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9023",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9024",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9025",
				"tone": "3"
			},
			{
				"sIds": [
					"779901",
					"779902"
				],
				"cId": "902501"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9026",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9027",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9028",
				"tone": "3"
			},
			{
				"sIds": [],
				"cId": "902801"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9029",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9030",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9031",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9032",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9033",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9034",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9035",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9036",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9037",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9038",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9039",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9040",
				"tone": "-1"
			},
			{
				"sIds": [],
				"cId": "90401"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9041",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9042",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9043",
				"tone": "6"
			},
			{
				"sIds": [
					"779903",
					"779904"
				],
				"cId": "904301"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9044",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9045",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9046",
				"tone": "6"
			},
			{
				"sIds": [],
				"cId": "904601"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9047",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9048",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9049",
				"tone": "-1"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9913"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9050",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9051",
				"tone": "-1"
			},
			{
				"sIds": [
					"779904",
					"779905"
				],
				"cId": "905101"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9052",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9053",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9054",
				"tone": "-1"
			},
			{
				"sIds": [
					"779907",
					"779908"
				],
				"cId": "905401"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9055",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9056",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9057",
				"tone": "8"
			},
			{
				"sIds": [
					"779908",
					"779909"
				],
				"cId": "905701"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9058",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9059",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9060",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9061",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9062",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9063",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9064",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9065",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9066",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9067",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9068",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9069",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9070",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9071",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9072",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9073",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9074",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9075",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9076",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9077",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9078",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9079",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9080",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9081",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9082",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9083",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9084",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9085",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9086",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9087",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9088",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9089",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9090",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9091",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9092",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9093",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9094",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9095",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9096",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9097",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9098",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9099",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9100",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9101",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9102",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9103",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9104",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9105",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9106",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9107",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9108",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9109",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9110",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9111",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9112",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9113",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9114",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9115",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9116",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9117",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9118",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9119",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9120",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9121",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9122",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9123",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9124",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9125",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9126",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9127",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9128",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9129",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9130",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9131",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9132",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9133",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9134",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9135",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9136",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9137",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9138",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9139",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9140",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"123"
				],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9141",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9142",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9143",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9144",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9145",
				"tone": "4"
			},
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy == 255"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9146",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9147",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9148",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9149",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9150",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9151",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9152",
				"tone": "5"
			},
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy == 255"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9153",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9154",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"123"
				],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"123"
				],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9155",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9156",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9157",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9158",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9159",
				"tone": "6"
			},
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy == 255"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9160",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9161",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9162",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9163",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9164",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9165",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9166",
				"tone": "7"
			},
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy == 255"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9167",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9168",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9169",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9170",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9171",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9172",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9173",
				"tone": "8"
			},
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy == 255"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9174",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9912",
				"cmd": "doy >= 249 && doy <= 255 && doy != 250"
			},
			{
				"sIds": [],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9175",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9911",
				"cmd": "doy >= 249 && doy <= 255"
			},
			{
				"sIds": [],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9176",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9177",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9178",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9179",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9180",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9181",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"123"
				],
				"cId": "9910",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9182",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"123"
				],
				"cId": "9909",
				"cmd": "doy >= 257 && doy <= 263"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9183",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9184",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9185",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9186",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9187",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9188",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9189",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9190",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9191",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9192",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9193",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9194",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9195",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9196",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9197",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9198",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9199",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9200",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9201",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9202",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9203",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9204",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9205",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9206",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9207",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9208",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9209",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9210",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9211",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9212",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9213",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9214",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9215",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9216",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9217",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9218",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9219",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9220",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9221",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9222",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9223",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9224",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9225",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9226",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9227",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9228",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9229",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9230",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9231",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9232",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9233",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9234",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9235",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9236",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9237",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 351"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9238",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9239",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9240",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9241",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9242",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9243",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9244",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 356"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9245",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9246",
				"tone": "3"
			},
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy == 359"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9247",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9248",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9249",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9250",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy == 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9251",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 356"
			},
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9252",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9253",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9904",
				"cmd": "doy == 359"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9254",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9255",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9256",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9257",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy == 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9258",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 356"
			},
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9259",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9260",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy == 359"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9261",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9262",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9263",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9264",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy == 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9265",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 356"
			},
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9266",
				"tone": "5"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9908",
				"cmd": "doy >= 344 && doy <= 350"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9267",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy == 359"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9268",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9269",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9270",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9271",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9905",
				"cmd": "doy == 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9272",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9907",
				"cmd": "doy >= 350 && doy <= 356"
			},
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9273",
				"tone": "6"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9906",
				"cmd": "doy >= 351 && doy <= 357"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9274",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9904",
				"cmd": "doy == 359"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9275",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9276",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9277",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9278",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"124"
				],
				"cId": "9905",
				"cmd": "doy == 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9279",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9905",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9280",
				"tone": "7"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"125"
				],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"125"
				],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [
					"124"
				],
				"cId": "9904",
				"cmd": "doy >= 359 && doy <= 364"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9281",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9282",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy == 0"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9283",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9284",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9285",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9286",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9903",
				"cmd": "doy == 363 || doy == 364 || (doy >= 0 && doy <= 4)"
			},
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [],
				"cId": "9287",
				"tone": "8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [],
				"cId": "9902",
				"cmd": "doy >= 0 && doy <= 4"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9288",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9289",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9290",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9291",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9292",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9293",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9901",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9294",
				"tone": "1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9295",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9296",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9297",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9298",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9299",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9300",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9301",
				"tone": "2"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9302",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9303",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9304",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9305",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9306",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9307",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9308",
				"tone": "3"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9309",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9310",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9311",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9312",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9313",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9314",
				"tone": "4"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9315",
				"tone": "4"
			}
		]
	}
] as const;
