// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { ServicePeriod } from "./types.ts";

export const SERVICE_RULES: ReadonlyArray<ServicePeriod> = [
	{
		"cmd": "nday >= 0 && nday < 7",
		"prime": [
			{
				"type": "Paschal"
			}
		],
		"terce": [
			{
				"type": "Paschal"
			}
		],
		"sexte": [
			{
				"type": "Paschal"
			}
		],
		"none": [
			{
				"type": "Paschal"
			}
		]
	},
	{
		"cmd": "nday >= 7 && nday < 39",
		"prime": [
			{
				"type": "Easter",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P,T}",
				"pickK": "1"
			}
		],
		"terce": [
			{
				"type": "Easter",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P,T}",
				"pickK": "1"
			}
		],
		"sexte": [
			{
				"type": "Easter",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P,T}",
				"pickK": "1"
			}
		],
		"none": [
			{
				"type": "Easter",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P,T}",
				"pickK": "1"
			}
		]
	},
	{
		"cmd": "nday >= 39 && nday < 57",
		"prime": [
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "nday == 40 || nday == 50"
			},
			{
				"type": "Normal",
				"troparion": "{M_A,T}",
				"pickT": "1",
				"kontakion": "{M_A,T}",
				"pickK": "1",
				"cmd": "nday > 40 && nday < 49"
			},
			{
				"type": "Normal",
				"troparion": "{M,M_A}",
				"pickT": "2",
				"kontakion": "{M,M_A,T}",
				"pickK": "1",
				"cmd": "nday > 40 && dRank == 3 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "nday == 49"
			}
		],
		"terce": [
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "nday == 40 || nday == 49"
			},
			{
				"type": "Normal",
				"troparion": "{M_A,T}",
				"pickT": "1",
				"kontakion": "{M_A,T}",
				"pickK": "1",
				"cmd": "nday >= 40 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{M,M_A}",
				"pickT": "2",
				"kontakion": "{M,M_A,T}",
				"pickK": "1",
				"cmd": "nday > 40 && dRank == 3 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "nday == 49"
			}
		],
		"sexte": [
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "nday == 40 || nday == 49"
			},
			{
				"type": "Normal",
				"troparion": "{M_A,T}",
				"pickT": "1",
				"kontakion": "{M_A,T}",
				"pickK": "1",
				"cmd": "nday >= 40 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{M,M_A}",
				"pickT": "2",
				"kontakion": "{M,M_A,T}",
				"pickK": "1",
				"cmd": "nday > 40 && dRank == 3 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "nday == 49"
			}
		],
		"none": [
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "nday == 40 || nday == 49"
			},
			{
				"type": "Normal",
				"troparion": "{M_A,T}",
				"pickT": "1",
				"kontakion": "{M_A,T}",
				"pickK": "1",
				"cmd": "nday >= 40 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{M,M_A}",
				"pickT": "2",
				"kontakion": "{M,M_A,T}",
				"pickK": "1",
				"cmd": "nday > 40 && dRank == 3 && nday != 49"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "nday == 49"
			}
		]
	},
	{
		"cmd": "nday >= 57 && doy <= 178",
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"cmd": "dow == 1 || dow == 2 || dow == 4"
			},
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"cmd": "dow == 3 || dow == 5"
			},
			{
				"type": "Lenten",
				"kontakion": "SatL",
				"pickK": "-1",
				"cmd": "dow == 6"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank == 3 || dRank == 2)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank == 3 || dRank == 2)"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		]
	},
	{
		"cmd": "(doy >= 179 && doy <= 211) || (doy >= 226 && doy <= 317) || (doy >= 358 && doy <= 364) || ((doy >= 0 || doy == 366) && nday <= -71)",
		"prime": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 2"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{M}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank >= 3"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow !=0 && dRank >= 2"
			}
		],
		"terce": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 2"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{M}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank >= 3"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow !=0 && dRank >= 2"
			}
		],
		"sexte": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 2"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{M}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank >= 3"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow !=0 && dRank >= 2"
			}
		],
		"none": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 2"
			},
			{
				"type": "Normal",
				"troparion": "{T,M}",
				"pickT": "2",
				"kontakion": "{M}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank >= 3"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow !=0 && dRank >= 2"
			}
		]
	},
	{
		"cmd": "doy > 211 && doy <= 225",
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"cmd": "dow == 1 || dow == 2 || dow == 4"
			},
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"cmd": "dow == 3 || dow == 5"
			},
			{
				"type": "Lenten",
				"kontakion": "SatL",
				"pickK": "-1",
				"cmd": "dow == 6"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank == 3 || dRank == 2)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank == 3 || dRank == 2)"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		]
	},
	{
		"cmd": "doy >= 318 && doy <= 357",
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"cmd": "dow == 1 || dow == 2 || dow == 4"
			},
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"cmd": "dow == 3 || dow == 5"
			},
			{
				"type": "Lenten",
				"kontakion": "SatL",
				"pickK": "-1",
				"cmd": "dow == 6"
			},
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank <= 6 && dRank >= 4)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow == 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && dRank == 8"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "1",
				"kontakion": "{M,T}",
				"pickK": "1",
				"cmd": "dow != 0 && (dRank == 3 || dRank == 2)"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dow == 0 && (dRank == 3 || dRank == 2)"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"cmd": "dow == 0"
			},
			{
				"type": "Normal",
				"troparion": "{M,T}",
				"pickT": "2",
				"kontakion": "{T}",
				"pickK": "1",
				"cmd": "dRank >= 2"
			}
		]
	},
	{
		"cmd": "nday >= -70 && nday <= -49",
		"prime": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			}
		],
		"terce": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			}
		],
		"sexte": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			}
		],
		"none": [
			{
				"type": "Normal",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{T}",
				"pickK": "1"
			}
		]
	},
	{
		"cmd": "nday >= -48 && nday <= -9",
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"cmd": "dow == 1"
			},
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"lentenK": "13",
				"cmd": "dow == 2"
			},
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"lentenK": "2",
				"cmd": "dow == 3"
			},
			{
				"type": "Lenten",
				"kontakion": "MTTL",
				"pickK": "-1",
				"lentenK": "9",
				"cmd": "dow == 4"
			},
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"cmd": "dow == 5"
			},
			{
				"type": "Lenten",
				"kontakion": "SatL",
				"pickK": "-1",
				"cmd": "dow == 6"
			},
			{
				"type": "Lenten",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Lenten",
				"lentenK": "7",
				"cmd": "dow == 1"
			},
			{
				"type": "Lenten",
				"lentenK": "14",
				"cmd": "dow == 2"
			},
			{
				"type": "Lenten",
				"lentenK": "3",
				"cmd": "dow == 3"
			},
			{
				"type": "Lenten",
				"lentenK": "10",
				"cmd": "dow == 4"
			},
			{
				"type": "Lenten",
				"lentenK": "19",
				"cmd": "dow == 5"
			},
			{
				"type": "Lenten",
				"cmd": "dow == 6"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Lenten",
				"lentenK": "8",
				"cmd": "dow == 1"
			},
			{
				"type": "Lenten",
				"lentenK": "15",
				"cmd": "dow == 2"
			},
			{
				"type": "Lenten",
				"lentenK": "4",
				"cmd": "dow == 3"
			},
			{
				"type": "Lenten",
				"lentenK": "11",
				"cmd": "dow == 4"
			},
			{
				"type": "Lenten",
				"lentenK": "20",
				"cmd": "dow == 5"
			},
			{
				"type": "Lenten",
				"cmd": "dow == 6"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"troparion": "{T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "Lenten",
				"lentenK": "9",
				"cmd": "dow == 1"
			},
			{
				"type": "Lenten",
				"lentenK": "16",
				"cmd": "dow == 2"
			},
			{
				"type": "Lenten",
				"lentenK": "5",
				"cmd": "dow == 3"
			},
			{
				"type": "Lenten",
				"lentenK": "12",
				"cmd": "dow == 4"
			},
			{
				"type": "Lenten",
				"cmd": "dow == 5"
			},
			{
				"type": "Lenten",
				"cmd": "dow == 6"
			}
		]
	},
	{
		"cmd": "nday >= -8 && nday <= -1",
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "{P,T}",
				"pickK": "1",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "None",
				"cmd": "dow == 5"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"kontakion": "{P,T}",
				"pickK": "1",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "None",
				"cmd": "dow == 5"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"kontakion": "{P,T}",
				"pickK": "1",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "None",
				"cmd": "dow == 5"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"kontakion": "{P,T}",
				"pickK": "1",
				"cmd": "dow != 0"
			},
			{
				"type": "Normal",
				"troparion": "{P,T}",
				"pickT": "1",
				"kontakion": "{P}",
				"pickK": "1",
				"cmd": "dow == 0"
			},
			{
				"type": "None",
				"cmd": "dow == 5"
			}
		]
	},
	{
		"prime": [
			{
				"type": "Lenten",
				"kontakion": "WFL",
				"pickK": "-1",
				"cmd": "nday == -51 || nday == -53"
			}
		],
		"terce": [
			{
				"type": "Lenten",
				"cmd": "nday == -51 || nday == -53"
			}
		],
		"sexte": [
			{
				"type": "Lenten",
				"cmd": "nday == -51 || nday == -53"
			}
		],
		"none": [
			{
				"type": "Lenten",
				"cmd": "nday == -51 || nday == -53"
			}
		]
	}
] as const;
