// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.
// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).
// Regenerate with `npm run codegen`.

import type { DayEntry } from "./types.ts";

export const TRIODION: ReadonlyArray<DayEntry | null> = [
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9801",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9802",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9803",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9804",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9805",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9806",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9807",
				"tone": "-1"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9808",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9809",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9810",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9811",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9812",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9813",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9814",
				"tone": "((ndayP - 49 - dow) / 7 + 7) % 8"
			},
			{
				"sIds": [
					"2593"
				],
				"cId": "2593"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9815",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"1"
				],
				"cId": "981501"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9816",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9817",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9818",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9819",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9820",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9821",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"986"
				],
				"cId": "986"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9822",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9913"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9823",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9824",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9825",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9826",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9827",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9828",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9829",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9913"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9830",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9831",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9832",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9833",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9834",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9835",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"543"
				],
				"cId": "543"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9836",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9913"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9837",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9838",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9839",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9840",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9841",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9842",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9843",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"2203"
				],
				"cId": "2203"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9844",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9845",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9846",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9847",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9848",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9849",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9850",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "991301"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9851",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9852",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9853",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9854",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9855",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9856",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9857",
				"tone": "((ndayP - dow) / 7) % 8"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9913"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9858",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9859",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9860",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9861",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9862",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9863",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9864",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9865",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9866",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9867",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9868",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [
					"0"
				],
				"cId": "9869",
				"tone": "((ndayP - dow) / 7) % 8"
			}
		]
	},
	{
		"saints": [
			{
				"sIds": [],
				"cId": "9900",
				"cmd": "doy >= 6 && doy <= 12"
			},
			{
				"sIds": [
					"0"
				],
				"cId": "9870",
				"tone": "(ndayP / 7) % 8"
			}
		]
	}
] as const;
