import { existsSync, readdirSync } from "node:fs";
import path from "node:path";
import type { Command, DayEntry } from "../../src/data/types.ts";
import { parseCommandsFile } from "./parseCommands.ts";
import { parseDayFile } from "./parseDay.ts";

const HEADER =
	"// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.\n" +
	"// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).\n" +
	"// Regenerate with `npm run codegen`.\n";

export interface EmittedFile {
	readonly relPath: string;
	readonly content: string;
}

/** Emit an array of DayEntry values keyed by numeric filename (01..N). */
export function emitCycle(
	name: "PENTECOSTARION" | "TRIODION",
	dir: string,
): EmittedFile {
	const files = readdirSync(dir)
		.filter((f) => /^\d+\.xml$/.test(f))
		.sort((a, b) => numericBasename(a) - numericBasename(b));
	const entries: (DayEntry | null)[] = [];
	for (const f of files) {
		const n = numericBasename(f);
		while (entries.length < n) entries.push(null);
		entries[n - 1] = parseDayFile(path.join(dir, f));
	}
	const body = [
		HEADER,
		`import type { DayEntry } from "./types.ts";\n`,
		`export const ${name}: ReadonlyArray<DayEntry | null> = ${json(entries)} as const;\n`,
	].join("\n");
	return {
		relPath: `${name.toLowerCase()}.ts`,
		content: body,
	};
}

/** Emit a menaion map keyed by MM-DD, over all months 01..12. */
export function emitMenaion(rootDir: string): EmittedFile {
	const map: Record<string, DayEntry> = {};
	for (let m = 1; m <= 12; m++) {
		const mm = m.toString().padStart(2, "0");
		const dir = path.join(rootDir, mm);
		if (!existsSync(dir)) continue;
		const files = readdirSync(dir).filter((f) => /^\d+\.xml$/.test(f));
		for (const f of files) {
			const d = numericBasename(f);
			const dd = d.toString().padStart(2, "0");
			map[`${mm}-${dd}`] = parseDayFile(path.join(dir, f));
		}
	}
	const body = [
		HEADER,
		`import type { DayEntry } from "./types.ts";\n`,
		`export const MENAION: Readonly<Record<string, DayEntry>> = ${json(sortKeys(map))} as const;\n`,
	].join("\n");
	return {
		relPath: "menaion.ts",
		content: body,
	};
}

/** Emit commands from a single Commands/*.xml file. */
export function emitCommands(
	exportName: string,
	file: string,
	relPath: string,
): EmittedFile {
	const commands: Command[] = parseCommandsFile(file);
	const body = [
		HEADER,
		`import type { Command } from "./types.ts";\n`,
		`export const ${exportName}: ReadonlyArray<Command> = ${json(commands)} as const;\n`,
	].join("\n");
	return { relPath, content: body };
}

function numericBasename(f: string): number {
	const m = /^(\d+)\.xml$/.exec(f);
	if (m === null || m[1] === undefined) throw new Error(`bad filename ${f}`);
	return parseInt(m[1], 10);
}

function sortKeys<T>(o: Record<string, T>): Record<string, T> {
	const out: Record<string, T> = {};
	for (const k of Object.keys(o).sort()) out[k] = o[k] as T;
	return out;
}

function json(v: unknown): string {
	return JSON.stringify(v, null, "\t");
}
