import { existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import type {
	Command,
	Commemoration,
	DayEntry,
	FastingPeriod,
	Life,
} from "../../src/data/types.ts";
import { parseCommandsFile } from "./parseCommands.ts";
import { parseDayFile } from "./parseDay.ts";
import { parseFastingFile } from "./parseFasting.ts";
import { parseLifeFile } from "./parseLife.ts";

const HEADER =
	"// AUTO-GENERATED by scripts/codegen — DO NOT EDIT.\n" +
	"// Source: vendor/ponomar/Ponomar/languages/xml (git submodule).\n" +
	"// Regenerate with `npm run codegen`.\n";

export interface EmittedFile {
	readonly relPath: string;
	readonly content: string;
}

/** Emit an array of DayEntry values keyed by numeric filename (01..N). */
export function emitCycle(
	name: "PENTECOSTARION" | "TRIODION",
	dir: string,
): EmittedFile {
	const files = readdirSync(dir)
		.filter((f) => /^\d+\.xml$/.test(f))
		.sort((a, b) => numericBasename(a) - numericBasename(b));
	const entries: (DayEntry | null)[] = [];
	for (const f of files) {
		const n = numericBasename(f);
		while (entries.length < n) entries.push(null);
		entries[n - 1] = parseDayFile(path.join(dir, f));
	}
	const body = [
		HEADER,
		`import type { DayEntry } from "./types.ts";\n`,
		`export const ${name}: ReadonlyArray<DayEntry | null> = ${json(entries)} as const;\n`,
	].join("\n");
	return {
		relPath: `${name.toLowerCase()}.ts`,
		content: body,
	};
}

/** Emit a menaion map keyed by MM-DD, over all months 01..12.
 *
 * Upstream stores menaion XML in two places:
 *   1. `languages/xml/{MM}/{DD}.xml`  — the newer canonical, language-neutral
 *      format. As of the pinned commit, only 01 and 12 are populated here.
 *   2. `languages/cu/xml/{MM}/{DD}.xml` — the older per-language Slavonic tree,
 *      which still covers all 12 months.
 *
 * For each MM-DD slot we prefer the canonical tree and fall back to the
 * Slavonic tree so we get complete year coverage. Both trees use identical
 * DAY/SAINT XML shape; only the corpus differs.
 */
export function emitMenaion(
	canonicalRoot: string,
	fallbackRoot: string,
): EmittedFile {
	const map: Record<string, DayEntry> = {};
	for (let m = 1; m <= 12; m++) {
		const mm = m.toString().padStart(2, "0");
		const canonicalDir = path.join(canonicalRoot, mm);
		const fallbackDir = path.join(fallbackRoot, mm);
		const seen = new Set<string>();
		if (existsSync(canonicalDir)) {
			for (const f of readdirSync(canonicalDir).filter((x) =>
				/^\d+\.xml$/.test(x),
			)) {
				const d = numericBasename(f);
				const dd = d.toString().padStart(2, "0");
				map[`${mm}-${dd}`] = parseDayFile(path.join(canonicalDir, f));
				seen.add(dd);
			}
		}
		if (existsSync(fallbackDir)) {
			for (const f of readdirSync(fallbackDir).filter((x) =>
				/^\d+\.xml$/.test(x),
			)) {
				const d = numericBasename(f);
				const dd = d.toString().padStart(2, "0");
				if (seen.has(dd)) continue;
				map[`${mm}-${dd}`] = parseDayFile(path.join(fallbackDir, f));
			}
		}
	}
	const body = [
		HEADER,
		`import type { DayEntry } from "./types.ts";\n`,
		`export const MENAION: Readonly<Record<string, DayEntry>> = ${json(sortKeys(map))} as const;\n`,
	].join("\n");
	return {
		relPath: "menaion.ts",
		content: body,
	};
}

/** Emit commands from a single Commands/*.xml file. */
export function emitCommands(
	exportName: string,
	file: string,
	relPath: string,
): EmittedFile {
	const commands: Command[] = parseCommandsFile(file);
	const body = [
		HEADER,
		`import type { Command } from "./types.ts";\n`,
		`export const ${exportName}: ReadonlyArray<Command> = ${json(commands)} as const;\n`,
	].join("\n");
	return { relPath, content: body };
}

/** Emit the ordered `<PERIOD>` list from Commands/Fasting.xml. */
export function emitFasting(file: string): EmittedFile {
	const periods: FastingPeriod[] = parseFastingFile(file);
	const body = [
		HEADER,
		`import type { FastingPeriod } from "./types.ts";\n`,
		`export const FASTING_RULES: ReadonlyArray<FastingPeriod> = ${json(periods)} as const;\n`,
	].join("\n");
	return { relPath: "fasting.ts", content: body };
}

/** Emit a commemorations map keyed by cId.
 *
 * Walks every `.xml` file under each of the given roots recursively. Files
 * whose root is neither `<SAINT>` nor `<COMMEMORATION>` are skipped. When
 * the same cId appears in multiple roots, records are **merged field-wise**:
 * name / church / info attributes union across sources and non-empty later
 * values win on individual attributes; scriptures concatenate.
 *
 * Files that yield only a `<LIFE>` element (with no NAME / CHURCH / INFO /
 * SCRIPTURE) do not produce a Commemoration entry — their body is captured
 * by `emitLives` instead.
 */
export function emitCommemorations(roots: readonly string[]): EmittedFile {
	const map: Record<string, Commemoration> = {};
	for (const root of roots) collectXmlFiles(root, (file, cId) => {
		const { commemoration } = parseLifeFile(file, cId);
		if (commemoration !== null) {
			map[cId] = mergeCommemoration(map[cId], commemoration);
		}
	});
	const body = [
		HEADER,
		`import type { Commemoration } from "./types.ts";\n`,
		`export const COMMEMORATIONS: Readonly<Record<string, Commemoration>> = ${json(sortKeys(map))} as const;\n`,
	].join("\n");
	return { relPath: "commemorations.ts", content: body };
}

/** Emit a lives map keyed by cId. Same walk semantics as `emitCommemorations`;
 * when a cId has entries in multiple roots, the record with a non-empty body
 * wins and any missing attribution fields fill from other sources. */
export function emitLives(roots: readonly string[]): EmittedFile {
	const map: Record<string, Life> = {};
	for (const root of roots) collectXmlFiles(root, (file, cId) => {
		const { life } = parseLifeFile(file, cId);
		if (life !== null) map[cId] = mergeLife(map[cId], life);
	});
	const body = [
		HEADER,
		`import type { Life } from "./types.ts";\n`,
		`export const LIVES: Readonly<Record<string, Life>> = ${json(sortKeys(map))} as const;\n`,
	].join("\n");
	return { relPath: "lives.ts", content: body };
}

function mergeCommemoration(
	older: Commemoration | undefined,
	newer: Commemoration,
): Commemoration {
	if (older === undefined) return newer;
	const merged: Commemoration = {
		cId: newer.cId,
		...mergeOptional("name", older.name, newer.name),
		...mergeOptional("church", older.church, newer.church),
		...mergeOptional("info", older.info, newer.info),
		scriptures: [...older.scriptures, ...newer.scriptures],
	};
	return merged;
}

function mergeOptional<K extends string, V extends object>(
	key: K,
	older: V | undefined,
	newer: V | undefined,
): Record<K, V> | Record<string, never> {
	if (older === undefined && newer === undefined) return {};
	const merged = { ...(older ?? {}), ...(newer ?? {}) } as V;
	if (Object.keys(merged).length === 0) return {};
	return { [key]: merged } as Record<K, V>;
}

function mergeLife(older: Life | undefined, newer: Life): Life {
	if (older === undefined) return newer;
	const preferBody = newer.body.length > 0 ? newer : older;
	const other = preferBody === newer ? older : newer;
	return {
		cId: newer.cId,
		body: preferBody.body,
		...pickDefined({
			id: preferBody.id ?? other.id,
			copyright: preferBody.copyright ?? other.copyright,
			translator: preferBody.translator ?? other.translator,
			repose: preferBody.repose ?? other.repose,
		}),
	};
}

function pickDefined<T extends object>(o: T): Partial<T> {
	const out: Partial<T> = {};
	for (const [k, v] of Object.entries(o)) {
		if (v !== undefined) (out as Record<string, unknown>)[k] = v;
	}
	return out;
}

function collectXmlFiles(
	root: string,
	onFile: (fullPath: string, cId: string) => void,
): void {
	if (!existsSync(root)) return;
	const stack: string[] = [root];
	while (stack.length > 0) {
		const dir = stack.pop() as string;
		for (const entry of readdirSync(dir)) {
			const full = path.join(dir, entry);
			const st = statSync(full);
			if (st.isDirectory()) {
				stack.push(full);
				continue;
			}
			if (!/\.xml$/.test(entry)) continue;
			const cId = entry.replace(/\.xml$/, "");
			onFile(full, cId);
		}
	}
}

function numericBasename(f: string): number {
	const m = /^(\d+)\.xml$/.exec(f);
	if (m === null || m[1] === undefined) throw new Error(`bad filename ${f}`);
	return parseInt(m[1], 10);
}

function sortKeys<T>(o: Record<string, T>): Record<string, T> {
	const out: Record<string, T> = {};
	for (const k of Object.keys(o).sort()) out[k] = o[k] as T;
	return out;
}

function json(v: unknown): string {
	return JSON.stringify(v, null, "\t");
}
