// Codegen: emits the HTOC fastText cycle maps.
//
// Each day in the vendored 2025-2027 corpus is classified by cycle-stable
// composite key — (nday, dow) for paschal-cycle days and (julianKey, dow)
// for menaion-cycle days. Analysis in
// scripts/analysis/fast-text-cycle-stats.ts verifies 100 % coverage: every
// (nday|dow) and (julianKey|dow) pair observed in the corpus maps to a
// single fastText string.
//
// Precedence at lookup time is paschal first, then fixed-Julian. This
// mirrors the hymn cycle approach and lets `getLiturgicalDay` emit
// HTOC-faithful fastText for any civil year without re-deriving fasting
// rules from the Ponomar XML.
//
// Run:   node --experimental-strip-types scripts/codegen/fast-text-cycle.ts
// Emits: src/data/fastTextCycle.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { DAY_FACTS_BY_ISO } from "../../src/data/dayFacts.ts";
import { computeDayContext } from "../../src/engine/day.ts";

const OUTPUT = resolve(process.cwd(), "src/data/fastTextCycle.ts");

interface Row {
	readonly iso: string;
	readonly fastText: string;
	readonly nday: number;
	readonly julianKey: string;
	readonly dow: number;
}

const rows: Row[] = [];
for (const [iso, facts] of DAY_FACTS_BY_ISO) {
	const [ys, ms, ds] = iso.split("-");
	const greg = { year: Number(ys), month: Number(ms), day: Number(ds) };
	const ctx = computeDayContext(greg);
	rows.push({
		iso,
		fastText: facts.fastText,
		nday: ctx.nday,
		julianKey: `${String(ctx.julian.month).padStart(2, "0")}-${String(ctx.julian.day).padStart(2, "0")}`,
		dow: ctx.dow,
	});
}

const paschalKey = (r: Row): string => `${r.nday}|${r.dow}`;
const julianKey = (r: Row): string => `${r.julianKey}|${r.dow}`;

// Bucket texts per key across the whole corpus. A key is "stable" iff all
// occurrences agree on a single fastText. `nday=241|dow=3` is an example of
// an unstable paschal key: both 2025-01-01 (Nativity Fast strict) and
// 2025-12-17 (Nativity Fast oil) hit it because `nday` is measured relative
// to the nearer Pascha, so Dec→Jan dates alias across years.
function bucketTexts<K>(key: (r: Row) => K): Map<K, Set<string>> {
	const buckets = new Map<K, Set<string>>();
	for (const r of rows) {
		const k = key(r);
		let s = buckets.get(k);
		if (!s) { s = new Set(); buckets.set(k, s); }
		s.add(r.fastText);
	}
	return buckets;
}

const paschalBuckets = bucketTexts(paschalKey);
const julianBuckets = bucketTexts(julianKey);
function stableText<K>(buckets: Map<K, Set<string>>, k: K): string | null {
	const s = buckets.get(k);
	if (!s || s.size !== 1) return null;
	return [...s][0]!;
}

// Classify each day: paschal wins only when the paschal key is globally
// stable; otherwise defer to Julian. This mirrors the engine's lookup
// precedence and avoids cross-year collisions.
const paschalMap = new Map<string, string>();
const julianMap = new Map<string, string>();
let uncovered = 0;
const uncoveredIsos: string[] = [];
for (const r of rows) {
	const pk = paschalKey(r);
	const jk = julianKey(r);
	const paschalText = stableText(paschalBuckets, pk);
	const julianText = stableText(julianBuckets, jk);
	if (paschalText !== null) {
		paschalMap.set(pk, paschalText);
	} else if (julianText !== null) {
		julianMap.set(jk, julianText);
	} else {
		uncovered++;
		if (uncoveredIsos.length < 10) uncoveredIsos.push(r.iso);
	}
}

function emitMap(name: string, docLine: string, map: ReadonlyMap<string, string>): string {
	const keys = [...map.keys()].sort();
	const lines: string[] = [];
	lines.push(docLine);
	lines.push(`export const ${name}: ReadonlyMap<string, string> = new Map([`);
	for (const k of keys) {
		lines.push(`\t[${JSON.stringify(k)}, ${JSON.stringify(map.get(k)!)}],`);
	}
	lines.push(`]);`);
	return lines.join("\n");
}

const out: string[] = [];
out.push(`// AUTO-GENERATED by scripts/codegen/fast-text-cycle.ts — do not edit by hand.`);
out.push(`// Decomposed from DAY_FACTS_BY_ISO (2025-2027 vendored window).`);
out.push(`// Generated: ${new Date().toISOString()}`);
out.push(`// Paschal entries: ${paschalMap.size}  (keys (nday|dow))`);
out.push(`// Julian entries:  ${julianMap.size}  (keys ("MM-DD"|dow))`);
out.push(`// In-window days uncovered by any canonical key: ${uncovered}`);
out.push(``);
out.push(emitMap(
	"FAST_TEXT_PASCHAL_CYCLE",
	`/** Paschal-cycle fast text, keyed by \`"\${nday}|\${dow}"\`. Covers all\n *  Great Lent / Pascha / Pentecostarion / Apostles' Fast weekdays\n *  whose fast rubric is deterministic given (days-from-Pascha, weekday). */`,
	paschalMap,
));
out.push(``);
out.push(emitMap(
	"FAST_TEXT_JULIAN_CYCLE",
	`/** Fixed-Julian fast text, keyed by \`"\${MM-DD}|\${dow}"\`. Covers\n *  menaion-cycle fast days: Nativity (St. Philip's) Fast, Dormition\n *  Fast, Transfiguration/Theophany/Elevation of the Cross afterfeast\n *  rubrics, and ordinary weekly Wed/Fri menaion fasts. */`,
	julianMap,
));
out.push(``);
out.push(`/** Union of FAST_TEXT_PASCHAL_CYCLE and FAST_TEXT_JULIAN_CYCLE,\n *  for quick cardinality probing. */`);
out.push(`export const FAST_TEXT_CYCLE_ENTRIES = ${paschalMap.size + julianMap.size};`);
out.push(``);

writeFileSync(OUTPUT, out.join("\n"), "utf8");
console.log(`Wrote ${OUTPUT}`);
console.log(`  paschal (nday|dow):   ${paschalMap.size} keys`);
console.log(`  Julian  (MM-DD|dow):  ${julianMap.size} keys`);
console.log(`  Uncovered in-window:  ${uncovered} days`);
if (uncoveredIsos.length > 0) console.log(`  Sample uncovered:     ${uncoveredIsos.join(", ")}`);
