// Codegen: harvest HTOC's canonical English commemoration text per cId
// and emit `src/data/htocNameOverlay.ts`. Iterates every day in the vendored
// corpus, calls `compareCommemorations` to find (htocText, engineCId) pairs,
// normalizes HTOC text (strip HTML, decode entities, trim trailing period),
// and picks the most frequent variant per cId (ties → shortest).
//
// Run:  node --experimental-strip-types scripts/codegen/htoc-name-overlay.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getLiturgicalDay } from "../../src/engine/index.ts";
import type { CalendarDate } from "../../src/core/calendar/pcalendar.ts";
import { compareCommemorations } from "../analysis/comparators.ts";
import { iterCorpus } from "../analysis/corpus.ts";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const OUT_PATH = resolve(HERE, "..", "..", "src", "data", "htocNameOverlay.ts");

function toCal(iso: string): CalendarDate {
	const [y, m, d] = iso.split("-").map((s) => Number.parseInt(s, 10));
	return { year: y!, month: m!, day: d! };
}

/** Normalize HTOC `text` for use as a canonical engine commemoration name:
 *  strip HTML tags (preserve inner text of `<sup>`), decode common entities,
 *  collapse whitespace, trim stray leading/trailing punctuation. */
function normalize(text: string): string {
	let t = text;
	// Preserve inner text of <sup>N</sup> → "N".
	t = t.replace(/<sup>([^<]*)<\/sup>/g, "$1");
	// Drop any other HTML tags.
	t = t.replace(/<[^>]+>/g, " ");
	// Decode a handful of common HTML entities.
	t = t
		.replace(/&nbsp;/g, " ")
		.replace(/&amp;/g, "&")
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&quot;/g, '"')
		.replace(/&apos;/g, "'")
		.replace(/&rsquo;|&lsquo;/g, "'")
		.replace(/&ldquo;|&rdquo;/g, '"')
		.replace(/&mdash;/g, "—")
		.replace(/&ndash;/g, "–")
		.replace(/&dagger;/g, "†");
	// Collapse whitespace.
	t = t.replace(/\s+/g, " ").trim();
	// Trim a sole trailing period or stray whitespace-period combinations
	// (HTOC rows commonly end with a lone ".").
	t = t.replace(/\s*\.\s*$/, "");
	return t;
}

interface Observation { text: string; count: number }
const perCid = new Map<string, Map<string, number>>();
let totalMatches = 0;

for (const { iso, day: htocDay } of iterCorpus()) {
	const cal = toCal(iso);
	const engineDay = getLiturgicalDay(cal);
	const cmp = compareCommemorations(htocDay.commemorations, engineDay.allSaints);
	for (const m of cmp.matched) {
		const engineSaint = engineDay.allSaints[m.engineIndex]!;
		const htocComm = htocDay.commemorations[m.htocIndex]!;
		const text = normalize(htocComm.text);
		if (text === "") continue;
		totalMatches++;
		const cId = engineSaint.cId;
		let bucket = perCid.get(cId);
		if (bucket === undefined) {
			bucket = new Map<string, number>();
			perCid.set(cId, bucket);
		}
		bucket.set(text, (bucket.get(text) ?? 0) + 1);
	}
}

// For each cId pick the canonical HTOC text: highest count, tiebreak on
// shortest length (prefer the base form over long multi-saint rows).
const resolved = new Map<string, Observation>();
for (const [cId, bucket] of perCid) {
	let best: { text: string; count: number } | null = null;
	for (const [text, count] of bucket) {
		if (
			best === null ||
			count > best.count ||
			(count === best.count && text.length < best.text.length)
		) {
			best = { text, count };
		}
	}
	if (best !== null) resolved.set(cId, best);
}

const sortedCids = [...resolved.keys()].sort();

const lines: string[] = [];
lines.push(
	"// AUTO-GENERATED by scripts/codegen/htoc-name-overlay.ts.",
	"// Do not hand-edit. Regenerate via",
	"//   node --experimental-strip-types scripts/codegen/htoc-name-overlay.ts",
	"//",
	"// Maps engine `cId` → the HTOC-canonical English commemoration text",
	"// observed across the vendored corpus (2025-01-01 … 2027-12-31).",
	"// Applied in `resolveSaints` to override `name.nominative` so engine",
	"// output matches HTOC's wording verbatim.",
	"",
	"export const HTOC_NAME_OVERLAY: Readonly<Record<string, string>> = Object.freeze({",
);
for (const cId of sortedCids) {
	const text = resolved.get(cId)!.text;
	lines.push(`\t${JSON.stringify(cId)}: ${JSON.stringify(text)},`);
}
lines.push("});", "");
lines.push(`export const HTOC_NAME_OVERLAY_SIZE = ${sortedCids.length};`, "");

writeFileSync(OUT_PATH, lines.join("\n"), "utf8");
process.stdout.write(
	`wrote ${OUT_PATH.replace(process.cwd(), "").replace(/\\/g, "/")} — ${sortedCids.length} cIds (${totalMatches} match observations)\n`,
);
