// Codegen: emits the paschal/triodion-cycle movable commemoration overlay.
// Consumes the shared classifier in `htoc-classify.ts`.
//
// Run:   node --experimental-strip-types scripts/codegen/htoc-paschal-movables.ts
// Emits: src/data/htocPaschalMovables.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { classifyAll } from "./htoc-classify.ts";

const OUTPUT = resolve(process.cwd(), "src/data/htocPaschalMovables.ts");

interface MovableEntry {
	readonly rank: string;
	readonly text: string;
	readonly minor: boolean;
	readonly lives: readonly { readonly name: string; readonly slug: string }[];
}

const byNday = new Map<number, Map<string, MovableEntry>>();

function entryKey(e: MovableEntry): string {
	return `${e.rank}|${e.minor ? 1 : 0}|${e.text}|${e.lives.map((l) => l.slug).join(",")}`;
}

for (const o of classifyAll()) {
	if (o.classification !== "paschal-movable") continue;
	if (!byNday.has(o.nday)) byNday.set(o.nday, new Map());
	const bucket = byNday.get(o.nday)!;
	const entry: MovableEntry = {
		rank: o.commem.rank,
		text: o.commem.text,
		minor: o.commem.minor,
		lives: o.commem.lives.map((l) => ({ name: l.name, slug: l.slug })),
	};
	const k = entryKey(entry);
	if (!bucket.has(k)) bucket.set(k, entry);
}

const sortedNdays = [...byNday.keys()].sort((a, b) => a - b);

const lines: string[] = [];
lines.push(`// AUTO-GENERATED by scripts/codegen/htoc-paschal-movables.ts — do not edit by hand.`);
lines.push(`// Decomposed from HTOC_DAY_FACTS_BY_ISO (2025-2027 vendored window).`);
lines.push(`// Generated: ${new Date().toISOString()}`);
lines.push(``);
lines.push(`import type { HtocCommemoration } from "./htocDayFacts.ts";`);
lines.push(``);
lines.push(`/** Paschal/triodion-cycle movable commemoration overlay, keyed by \`nday\``);
lines.push(` *  (days-relative-to-Pascha, Pascha=0). A text lives here iff every one`);
lines.push(` *  of its vendored occurrences shared the same nday value while landing`);
lines.push(` *  on different Julian dates. DOW-nearest-Julian-date patterns go to`);
lines.push(` *  Phase C4. */`);
lines.push(
	`export const HTOC_PASCHAL_MOVABLES_CYCLE: ReadonlyMap<number, readonly HtocCommemoration[]> = new Map([`,
);
let total = 0;
for (const n of sortedNdays) {
	const entries = [...byNday.get(n)!.values()].sort((a, b) => a.text.localeCompare(b.text));
	total += entries.length;
	lines.push(`\t[${n}, [`);
	for (const e of entries) {
		const livesJson = JSON.stringify(e.lives);
		lines.push(
			`\t\t{ rank: ${JSON.stringify(e.rank)}, text: ${JSON.stringify(e.text)}, minor: ${e.minor}, lives: ${livesJson} },`,
		);
	}
	lines.push(`\t]],`);
}
lines.push(`]);`);
lines.push(``);
lines.push(`/** Total number of paschal/triodion movable entries captured. */`);
lines.push(`export const HTOC_PASCHAL_MOVABLES_COUNT = ${total};`);
lines.push(``);

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(`Wrote ${OUTPUT}`);
console.log(`  ${sortedNdays.length} distinct nday keys`);
console.log(`  ${total} paschal-movable entries`);
