// Codegen: emits the fixed-Julian commemoration cycle.
// Consumes the shared classifier in `htoc-classify.ts`.
//
// Run:   node --experimental-strip-types scripts/codegen/htoc-fixed-commemorations.ts
// Emits: src/data/htocFixedCommemorations.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { classifyAll } from "./htoc-classify.ts";

const OUTPUT = resolve(process.cwd(), "src/data/htocFixedCommemorations.ts");

interface FixedEntry {
	readonly rank: string;
	readonly text: string;
	readonly minor: boolean;
	readonly lives: readonly { readonly name: string; readonly slug: string }[];
}

const byJulian = new Map<string, Map<string, FixedEntry>>();

function entryKey(e: FixedEntry): string {
	return `${e.rank}|${e.minor ? 1 : 0}|${e.text}|${e.lives.map((l) => l.slug).join(",")}`;
}

const counts = { "fixed-julian": 0, "paschal-movable": 0, "dow-shift": 0, "season-synth": 0, transferred: 0 };

for (const o of classifyAll()) {
	counts[o.classification]++;
	if (o.classification !== "fixed-julian") continue;
	if (!byJulian.has(o.julianKey)) byJulian.set(o.julianKey, new Map());
	const bucket = byJulian.get(o.julianKey)!;
	const entry: FixedEntry = {
		rank: o.commem.rank,
		text: o.commem.text,
		minor: o.commem.minor,
		lives: o.commem.lives.map((l) => ({ name: l.name, slug: l.slug })),
	};
	const k = entryKey(entry);
	if (!bucket.has(k)) bucket.set(k, entry);
}

const sortedKeys = [...byJulian.keys()].sort();

const lines: string[] = [];
lines.push(`// AUTO-GENERATED by scripts/codegen/htoc-fixed-commemorations.ts — do not edit by hand.`);
lines.push(`// Decomposed from HTOC_DAY_FACTS_BY_ISO (2025-2027 vendored window).`);
lines.push(`// Generated: ${new Date().toISOString()}`);
lines.push(`// Fixed-Julian occurrences:    ${counts["fixed-julian"]}`);
lines.push(`// Paschal-movable (Phase C2):  ${counts["paschal-movable"]}`);
lines.push(`// DOW-shift (Phase C4):        ${counts["dow-shift"]}`);
lines.push(`// Season-synth (runtime):      ${counts["season-synth"]}`);
lines.push(`// Transferred (Phase C5):      ${counts.transferred}`);
lines.push(``);
lines.push(`import type { HtocCommemoration } from "./htocDayFacts.ts";`);
lines.push(``);
lines.push(`/** Fixed-Julian commemoration cycle: keyed by Julian \`"MM-DD"\`.`);
lines.push(` *  Includes multi-day fixed feasts (one entry per Julian date in their`);
lines.push(` *  span). Movable overlays and season markers live elsewhere. */`);
lines.push(
	`export const HTOC_FIXED_COMMEMORATIONS_CYCLE: ReadonlyMap<string, readonly HtocCommemoration[]> = new Map([`,
);
let total = 0;
for (const k of sortedKeys) {
	const entries = [...byJulian.get(k)!.values()].sort((a, b) => a.text.localeCompare(b.text));
	total += entries.length;
	lines.push(`\t[${JSON.stringify(k)}, [`);
	for (const e of entries) {
		const livesJson = JSON.stringify(e.lives);
		lines.push(
			`\t\t{ rank: ${JSON.stringify(e.rank)}, text: ${JSON.stringify(e.text)}, minor: ${e.minor}, lives: ${livesJson} },`,
		);
	}
	lines.push(`\t]],`);
}
lines.push(`]);`);
lines.push(``);
lines.push(`/** Total number of fixed-Julian commemoration entries across the cycle. */`);
lines.push(`export const HTOC_FIXED_COMMEMORATIONS_COUNT = ${total};`);
lines.push(``);

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(`Wrote ${OUTPUT}`);
console.log(`  ${sortedKeys.length} Julian keys`);
console.log(`  ${total} fixed-Julian unique entries`);
console.log(`  occurrences: fixed=${counts["fixed-julian"]} paschal=${counts["paschal-movable"]} dowShift=${counts["dow-shift"]} season=${counts["season-synth"]} transferred=${counts.transferred}`);
