// Codegen for `src/data/htocDailyLectionary.ts`.
//
// Extracts every "no-note" Liturgy scripture citation from the HTOC corpus
// fixtures (`tests/fixtures/htoc-full-*.json`), keys each by `(ndayF, doy)`
// — the pair we've verified is deterministic and collision-free across
// years — and emits a static TS module. Runs manually via
// `node --experimental-strip-types scripts/codegen/htoc-daily-lectionary.ts`.
//
// The key insight from `scripts/analysis/derive-daily-lectionary.ts`:
// 880 no-note slots across 2025–2027 map to 880 distinct `(ndayF, doy)`
// keys with zero collisions. That means the HTOC daily lectionary can be
// mirrored losslessly by a hash table.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { BibleRef } from "../../src/bible/types.ts";
import { computeDayContext } from "../../src/engine/day.ts";
import { tryParseCitation } from "../analysis/comparators.ts";
import type { HtocCorpus } from "../analysis/corpus.ts";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const FIXTURES_DIR = resolve(HERE, "..", "..", "tests", "fixtures");
const OUT_PATH = resolve(HERE, "..", "..", "src", "data", "htocDailyLectionary.ts");
const YEARS = [2025, 2026, 2027] as const;

const GOSPEL_BOOKS = new Set(["Mt", "Mk", "Lk", "Jn"]);

/** Format a parsed BibleRef as Ponomar-style "Short_C:V,V" using the
 *  canonical short book name (e.g. `"Heb_11:8, 16"`, not `"Hebrews_..."`). */
function ponomarStyle(ref: BibleRef): string {
	if (ref.ranges.length === 0) return `${ref.bookShort}_${ref.chapter}`;
	const parts = ref.ranges.map((r) => {
		const startSame = r.start.chapter === ref.chapter;
		const endSame = r.end.chapter === ref.chapter;
		const startChap = startSame ? "" : `${r.start.chapter}:`;
		const endChap = endSame ? "" : `${r.end.chapter}:`;
		const startPart = r.start.part ?? "";
		const endPart = r.end.part ?? "";
		const s = `${startChap}${r.start.verse}${startPart}`;
		const e = `${endChap}${r.end.verse}${endPart}`;
		return r.start.chapter === r.end.chapter && r.start.verse === r.end.verse
			? s
			: `${s}-${e}`;
	});
	return `${ref.bookShort}_${ref.chapter}:${parts.join(", ")}`;
}

function loadCorpus(year: number): HtocCorpus | null {
	const p = resolve(FIXTURES_DIR, `htoc-full-${year}.json`);
	if (!existsSync(p)) return null;
	return JSON.parse(readFileSync(p, "utf8")) as HtocCorpus;
}

function isoToCal(iso: string): { year: number; month: number; day: number } {
	const [y, m, d] = iso.split("-").map((s) => Number.parseInt(s, 10));
	return { year: y!, month: m!, day: d! };
}

interface Entry {
	readonly type: "apostol" | "gospel";
	readonly reading: string;
}

interface Slot {
	readonly key: string;
	readonly entries: readonly Entry[];
	readonly firstSeenIso: string;
}

const slots = new Map<string, Slot>();
let totalNoNote = 0;
let skippedUnparseable = 0;

for (const year of YEARS) {
	const c = loadCorpus(year);
	if (c === null) continue;
	for (const iso of Object.keys(c.days)) {
		const htoc = c.days[iso]!;
		const cal = isoToCal(iso);
		const ctx = computeDayContext(cal);
		const key = `${ctx.ndayF},${ctx.doy}`;
		const entries: Entry[] = [];
		for (const s of htoc.scripture) {
			const note = (s.note ?? "").trim();
			if (note !== "") continue;
			totalNoNote++;
			const parsed = tryParseCitation(s.citation);
			if (parsed === null) {
				skippedUnparseable++;
				continue;
			}
			const type: "apostol" | "gospel" = GOSPEL_BOOKS.has(parsed.book)
				? "gospel"
				: "apostol";
			entries.push({ type, reading: ponomarStyle(parsed) });
		}
		if (entries.length === 0) continue;
		const existing = slots.get(key);
		if (existing === undefined) {
			slots.set(key, { key, entries, firstSeenIso: iso });
			continue;
		}
		const existingSig = existing.entries.map((e) => `${e.type}:${e.reading}`).join("|");
		const newSig = entries.map((e) => `${e.type}:${e.reading}`).join("|");
		if (existingSig !== newSig) {
			console.warn(
				`COLLISION on key=${key}: ${existing.firstSeenIso} → [${existingSig}] vs ${iso} → [${newSig}]`,
			);
		}
	}
}

const sorted = [...slots.entries()].sort((a, b) => a[0].localeCompare(b[0]));

const banner = `// AUTO-GENERATED by scripts/codegen/htoc-daily-lectionary.ts.
// Do not hand-edit. Regenerate via
//   node --experimental-strip-types scripts/codegen/htoc-daily-lectionary.ts
//
// Sourced from tests/fixtures/htoc-full-{2025,2026,2027}.json.
// Keys are "\${ndayF},\${doy}" (both integers, using upstream Ponomar's
// Julian-civil-year conventions). Values are the ordered list of
// no-note Liturgy scriptures HTOC lists on that slot — matching the
// classical Byzantine daily rjadovoje (ordinary sequential) lectionary
// under HTOC's ROCOR/Jordanville recension.

export interface HtocDailyLectionaryEntry {
	readonly type: "apostol" | "gospel";
	/** Ponomar-style reading, e.g. \`"II Tim_4:9-22"\`. */
	readonly reading: string;
}

`;

const body: string[] = [];
body.push(
	`export const HTOC_DAILY_LECTIONARY: ReadonlyMap<string, readonly HtocDailyLectionaryEntry[]> = new Map([`,
);
for (const [key, slot] of sorted) {
	const items = slot.entries
		.map((e) => `{ type: "${e.type}", reading: ${JSON.stringify(e.reading)} }`)
		.join(", ");
	body.push(`\t[${JSON.stringify(key)}, [${items}]],`);
}
body.push(`]);`);
body.push("");
body.push(
	`/** Total slots covered by the emitted table — sanity check for consumers. */`,
);
body.push(`export const HTOC_DAILY_LECTIONARY_SIZE = ${sorted.length};`);
body.push("");

writeFileSync(OUT_PATH, banner + body.join("\n"), "utf8");
console.log(
	`wrote ${OUT_PATH.replace(process.cwd(), "").replace(/\\/g, "/")} — ${sorted.length} slots (${totalNoNote} no-note refs total, ${skippedUnparseable} unparseable)`,
);
