// Codegen: reads `scratch/htoc-days.json` (produced by the full day-level
// scraper) and emits `src/data/htocDayFacts.ts` — a per-ISO-date lookup
// table of HTOC's `headerText`, `tone`, `fastText`, `troparia`, and
// `kontakia`. These are the display-oriented day facts HTOC publishes in
// addition to the saint commemoration list (vendored separately in
// `htocSaints.ts`) and the daily lectionary (vendored in
// `htocDailyLectionary.ts`).
//
// Run:   node --experimental-strip-types scripts/codegen/htoc-day-facts.ts
// Reads: scratch/htoc-days.json
// Emits: src/data/htocDayFacts.ts

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface RawHymnSaint {
	readonly name: string;
	readonly href: string;
}
interface RawHymn {
	readonly title: string;
	readonly text: string;
	readonly group: number;
	readonly saints: readonly RawHymnSaint[];
}
interface RawDay {
	readonly headerText: string;
	readonly tone: number | string;
	readonly fastText: string;
	readonly troparia: readonly RawHymn[];
	readonly kontakia: readonly RawHymn[];
}
interface RawFile {
	readonly source: string;
	readonly years: readonly number[];
	readonly generatedAt: string;
	readonly count: number;
	readonly days: Readonly<Record<string, RawDay>>;
}

const INPUT = resolve(process.cwd(), "scratch/htoc-days.json");
const OUTPUT = resolve(process.cwd(), "src/data/htocDayFacts.ts");

const raw = JSON.parse(readFileSync(INPUT, "utf8")) as RawFile;

/** Extract the stable `Month/DD-NN` slug from an HTOC href URL. */
function hrefToSlug(href: string): string {
	const m = href.match(/\/los\/([^/]+\/[^.]+)/);
	return m?.[1] ?? href;
}

interface EmittedHymnSaint {
	readonly name: string;
	readonly slug: string;
}
interface EmittedHymn {
	readonly title: string;
	readonly text: string;
	readonly group: number;
	readonly saints: readonly EmittedHymnSaint[];
}
interface EmittedDay {
	readonly headerText: string;
	readonly tone: number | null;
	readonly fastText: string;
	readonly troparia: readonly EmittedHymn[];
	readonly kontakia: readonly EmittedHymn[];
}

function normalizeHymn(h: RawHymn): EmittedHymn {
	return {
		title: h.title,
		text: h.text,
		group: h.group,
		saints: (h.saints ?? []).map((s) => ({ name: s.name, slug: hrefToSlug(s.href) })),
	};
}

const emitted = new Map<string, EmittedDay>();
let totalTroparia = 0;
let totalKontakia = 0;
for (const [iso, day] of Object.entries(raw.days)) {
	const tone = typeof day.tone === "number" ? day.tone : null;
	const troparia = (day.troparia ?? []).map(normalizeHymn);
	const kontakia = (day.kontakia ?? []).map(normalizeHymn);
	totalTroparia += troparia.length;
	totalKontakia += kontakia.length;
	emitted.set(iso, {
		headerText: day.headerText ?? "",
		tone,
		fastText: day.fastText ?? "",
		troparia,
		kontakia,
	});
}

const sortedDates = [...emitted.keys()].sort();

const lines: string[] = [];
lines.push(
	"// AUTO-GENERATED by scripts/codegen/htoc-day-facts.ts — do not edit by hand.",
	"// Source: scratch/htoc-days.json (scraped from holytrinityorthodox.com).",
	`// Generated: ${new Date().toISOString()}`,
	`// Years covered: ${raw.years.join(", ")}`,
	"",
	"/** A single HTOC-published hymn (troparion or kontakion) for one day. */",
	"export interface HtocHymn {",
	'\t/** Display title, e.g. `"Troparion, Tone IV"` or `"Holy Martyr Boniface"`. */',
	"\treadonly title: string;",
	'\t/** Hymn text. `"No Troparion is given for this service in the Menaion."` is',
	"\t *  used as a placeholder on days with no troparion for the ranked saint. */",
	"\treadonly text: string;",
	"\t/** Order-group as scraped from HTOC (used to recover display order on days",
	"\t *  with multiple saints). */",
	"\treadonly group: number;",
	"\t/** Saints this hymn is attached to. `slug` matches `HtocSaint.slug` so a",
	"\t *  consumer can join propers to the day's commemoration list without any",
	"\t *  cId lookup. May be empty for day-level (resurrectional / feast) propers. */",
	"\treadonly saints: readonly { readonly name: string; readonly slug: string }[];",
	"}",
	"",
	"/** HTOC day-level facts: title line, tone, fast rule, and the day's propers. */",
	"export interface HtocDayFacts {",
	'\t/** Header line as scraped, e.g. `"28th Week after Pentecost. Tone two."`. */',
	"\treadonly headerText: string;",
	"\t/** Resurrectional tone of the week (1..8), or `null` on Bright Week and",
	"\t *  Great Feasts of the Lord where HTOC does not print a tone. */",
	"\treadonly tone: number | null;",
	'\t/** Fast-rule display string, e.g. `"Nativity (St. Philip\'s Fast). By',
	'\t *  Monastic Charter: Strict Fast (Bread, Vegetables, Fruits)"`. Empty',
	"\t *  string on non-fast days. */",
	"\treadonly fastText: string;",
	"\t/** Day's troparia in HTOC publication order. */",
	"\treadonly troparia: readonly HtocHymn[];",
	"\t/** Day's kontakia in HTOC publication order. */",
	"\treadonly kontakia: readonly HtocHymn[];",
	"}",
	"",
	"/** ISO-date → HTOC day facts for that day.",
	" *  Coverage: 2025-01-01 through 2027-12-31 (vendored corpus window). */",
	"export const HTOC_DAY_FACTS_BY_ISO: ReadonlyMap<string, HtocDayFacts> = new Map([",
);
for (const iso of sortedDates) {
	const f = emitted.get(iso)!;
	lines.push(`\t[${JSON.stringify(iso)}, ${JSON.stringify(f)}],`);
}
lines.push(
	"]);",
	"",
	`/** Total number of troparia entries across the vendored window. */`,
	`export const HTOC_DAY_FACTS_TROPARIA_COUNT = ${totalTroparia};`,
	`/** Total number of kontakia entries across the vendored window. */`,
	`export const HTOC_DAY_FACTS_KONTAKIA_COUNT = ${totalKontakia};`,
	"",
);

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(
	`wrote ${OUTPUT.replace(process.cwd(), "")} — ${emitted.size} days, ${totalTroparia} troparia, ${totalKontakia} kontakia`,
);
