// Codegen: reads `scratch/htoc-saints.json` (produced by the recon script)
// and emits `src/data/htocSaints.ts` — a per-ISO-date lookup table of HTOC
// saint commemorations with rank glyphs, canonical URL, name list, and
// display text. Keyed by ISO date so lookups are trivially deterministic.
//
// Run:   node --experimental-strip-types scripts/codegen/htoc-saints.ts
// Reads: scratch/htoc-saints.json
// Emits: src/data/htocSaints.ts

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface HtocSaintRecord {
	readonly href: string;
	readonly cycle: "fixed" | "movable";
	readonly names: readonly string[];
	readonly ranks: readonly string[];
	readonly texts: readonly string[];
	readonly dates: readonly string[];
}

interface HtocSaintsFile {
	readonly source: string;
	readonly years: readonly number[];
	readonly generatedAt: string;
	readonly count: number;
	readonly saints: readonly HtocSaintRecord[];
}

const INPUT = resolve(process.cwd(), "scratch/htoc-saints.json");
const OUTPUT = resolve(process.cwd(), "src/data/htocSaints.ts");

const raw = JSON.parse(readFileSync(INPUT, "utf8")) as HtocSaintsFile;

interface EmittedEntry {
	readonly slug: string;
	readonly cycle: "fixed" | "movable";
	readonly names: readonly string[];
	readonly rank: string;
	readonly text: string;
}

const byDate = new Map<string, EmittedEntry[]>();
for (const s of raw.saints) {
	// Derive a stable per-canonical slug from the href tail.
	// `.../los/April/01-01.htm` → `April/01-01`
	// `.../los/Epiphany/e10121-...htm` → `Epiphany/e10121-...`
	const m = s.href.match(/\/los\/([^/]+\/[^.]+)/);
	const slug = m?.[1] ?? s.href;
	// Ranks & texts are position-aligned with names. Emit one entry per
	// canonical saint with the max rank glyph and first text.
	const rank = s.ranks[0] ?? "0";
	const text = s.texts[0] ?? "";
	const entry: EmittedEntry = {
		slug,
		cycle: s.cycle,
		names: s.names,
		rank,
		text,
	};
	for (const iso of s.dates) {
		let bucket = byDate.get(iso);
		if (bucket === undefined) {
			bucket = [];
			byDate.set(iso, bucket);
		}
		bucket.push(entry);
	}
}

const sortedDates = [...byDate.keys()].sort();

const lines: string[] = [];
lines.push(
	"// AUTO-GENERATED by scripts/codegen/htoc-saints.ts — do not edit by hand.",
	"// Source: scratch/htoc-saints.json (scraped from holytrinityorthodox.com).",
	`// Generated: ${new Date().toISOString()}`,
	`// Years covered: ${raw.years.join(", ")}`,
	"",
	"/** A single HTOC saint commemoration for one ISO date. */",
	"export interface HtocSaint {",
	'\t/** Stable slug derived from the HTOC URL, e.g. `"April/01-01"`. */',
	"\treadonly slug: string;",
	'\t/** `"fixed"` for menaion-cycle entries; `"movable"` for pentecostarion. */',
	'\treadonly cycle: "fixed" | "movable";',
	'\t/** Canonical name list, e.g. `["Basilides", "Geroncius"]`. */',
	"\treadonly names: readonly string[];",
	"\t/** HTOC rank glyph. Numeric strings (0..6) or `\"o\"` for un-graded. */",
	"\treadonly rank: string;",
	"\t/** Display text as scraped from HTOC. */",
	"\treadonly text: string;",
	"}",
	"",
	"/** ISO-date → HTOC saint commemorations for that day.",
	" *  Coverage: 2025-01-01 through 2027-12-31 (vendored corpus window). */",
	"export const HTOC_SAINTS_BY_ISO: ReadonlyMap<string, readonly HtocSaint[]> = new Map([",
);
for (const iso of sortedDates) {
	const bucket = byDate.get(iso)!;
	const entries = bucket
		.map(
			(e) =>
				`{ slug: ${JSON.stringify(e.slug)}, cycle: ${JSON.stringify(e.cycle)}, names: ${JSON.stringify(e.names)}, rank: ${JSON.stringify(e.rank)}, text: ${JSON.stringify(e.text)} }`,
		)
		.join(", ");
	lines.push(`\t[${JSON.stringify(iso)}, [${entries}]],`);
}
lines.push(
	"]);",
	"",
	"/** Total number of (iso, saint) rows. */",
	`export const HTOC_SAINTS_ROW_COUNT = ${raw.saints.reduce((n, s) => n + s.dates.length, 0)};`,
	"",
);

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(
	`wrote ${OUTPUT.replace(process.cwd(), "")} — ${byDate.size} dates, ${raw.saints.length} canonical saints, ${raw.saints.reduce((n, s) => n + s.dates.length, 0)} rows`,
);
